// Error catalog from docs/spec/05-api.md §1. test/errors.test.ts checks it against docs/spec/vectors/errors.json.

import { z } from "zod";

export const errorCodeValues = [
  "UNAUTHENTICATED",
  "FORBIDDEN",
  "SUPPORT_READ_ONLY",
  "NOT_FOUND",
  "VALIDATION_FAILED",
  "INVALID_TRANSITION",
  "STALE_BILL",
  "RATE_LIMITED",
  "INTERNAL",
  "INVALID_CREDENTIALS",
  "ACCOUNT_LOCKED",
  "PASSWORD_POLICY",
  "TOKEN_INVALID",
  "LINE_TOKEN_INVALID",
  "NOT_REGISTERED",
  "LAST_OWNER",
  "EMAIL_TAKEN",
  "SLUG_TAKEN",
  "CODE_TAKEN",
  "IN_USE",
  "SIZE_TIER_OVERLAP",
  "INVALID_PHONE",
  "LINK_REQUEST_PENDING",
  "MODULE_DISABLED",
  "BRANCH_CLOSED",
  "OUTSIDE_BOOKING_WINDOW",
  "SLOT_TAKEN",
  "ROOM_TAKEN",
  "PET_ALREADY_BOOKED",
  "DAYCARE_FULL",
  "PRICE_NOT_FOUND",
  "WEIGHT_REQUIRED",
  "DURATION_ZERO",
  "INVALID_DATE_RANGE",
  "CUSTOMER_BLACKLISTED",
  "PET_INACTIVE",
  "SPECIES_NOT_ALLOWED",
  "BREED_REJECTED",
  "PET_TOO_HEAVY",
  "PET_TOO_YOUNG",
  "IN_HEAT_NOT_ALLOWED",
  "REACTIVE_NOT_ALLOWED",
  "VACCINE_REQUIRED",
  "STATUS_NOT_ALLOWED",
  "TOO_LATE_TO_RESCHEDULE",
  "RESCHEDULE_LIMIT",
  "HOLD_EXPIRED",
  "CONSENT_REQUIRED",
  "INTAKE_INCOMPLETE",
  "PROMPTPAY_NOT_CONFIGURED",
  "INVALID_PROMPTPAY_ID",
  "DUPLICATE_SLIP_CONFIRM_REQUIRED",
  "INVALID_AMOUNT",
  "AMOUNT_EXCEEDS_DUE",
  "INSUFFICIENT_CREDIT",
  "BILL_ALREADY_PAID",
  "BILL_HAS_DUE",
  "BILL_NOT_OPEN",
  "LINE_DISCOUNT_TOO_LARGE",
  "BILL_DISCOUNT_TOO_LARGE",
  "DISCOUNT_LIMIT_EXCEEDED",
  "REASON_REQUIRED",
  "PACKAGE_NOT_ACTIVE",
  "PACKAGE_EXHAUSTED",
  "PACKAGE_EXPIRED",
  "PACKAGE_SERVICE_MISMATCH",
  "PACKAGE_SIZE_MISMATCH",
  "PACKAGE_PET_MISMATCH",
  "UPLOAD_KIND_NOT_ALLOWED",
  "UPLOAD_TYPE_NOT_ALLOWED",
  "UPLOAD_TOO_LARGE",
  "FILE_NOT_UPLOADED",
  "LINE_NOT_CONNECTED",
  "LINE_API_ERROR",
  "WEBHOOK_SIGNATURE_INVALID",
  "IMPORT_HAS_ERRORS",
  "CRON_FORBIDDEN",
] as const;
export const errorCode = z.enum(errorCodeValues);
export type ErrorCode = z.infer<typeof errorCode>;

export const ERROR_HTTP = {
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  SUPPORT_READ_ONLY: 403,
  NOT_FOUND: 404,
  VALIDATION_FAILED: 422,
  INVALID_TRANSITION: 409,
  STALE_BILL: 409,
  RATE_LIMITED: 429,
  INTERNAL: 500,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 423,
  PASSWORD_POLICY: 422,
  TOKEN_INVALID: 400,
  LINE_TOKEN_INVALID: 401,
  NOT_REGISTERED: 403,
  LAST_OWNER: 409,
  EMAIL_TAKEN: 409,
  SLUG_TAKEN: 409,
  CODE_TAKEN: 409,
  IN_USE: 409,
  SIZE_TIER_OVERLAP: 422,
  INVALID_PHONE: 422,
  LINK_REQUEST_PENDING: 409,
  MODULE_DISABLED: 422,
  BRANCH_CLOSED: 422,
  OUTSIDE_BOOKING_WINDOW: 422,
  SLOT_TAKEN: 409,
  ROOM_TAKEN: 409,
  PET_ALREADY_BOOKED: 409,
  DAYCARE_FULL: 409,
  PRICE_NOT_FOUND: 422,
  WEIGHT_REQUIRED: 422,
  DURATION_ZERO: 422,
  INVALID_DATE_RANGE: 422,
  CUSTOMER_BLACKLISTED: 403,
  PET_INACTIVE: 422,
  SPECIES_NOT_ALLOWED: 422,
  BREED_REJECTED: 422,
  PET_TOO_HEAVY: 422,
  PET_TOO_YOUNG: 422,
  IN_HEAT_NOT_ALLOWED: 422,
  REACTIVE_NOT_ALLOWED: 422,
  VACCINE_REQUIRED: 422,
  STATUS_NOT_ALLOWED: 409,
  TOO_LATE_TO_RESCHEDULE: 422,
  RESCHEDULE_LIMIT: 422,
  HOLD_EXPIRED: 410,
  CONSENT_REQUIRED: 422,
  INTAKE_INCOMPLETE: 422,
  PROMPTPAY_NOT_CONFIGURED: 422,
  INVALID_PROMPTPAY_ID: 422,
  DUPLICATE_SLIP_CONFIRM_REQUIRED: 409,
  INVALID_AMOUNT: 422,
  AMOUNT_EXCEEDS_DUE: 422,
  INSUFFICIENT_CREDIT: 422,
  BILL_ALREADY_PAID: 409,
  BILL_HAS_DUE: 409,
  BILL_NOT_OPEN: 409,
  LINE_DISCOUNT_TOO_LARGE: 422,
  BILL_DISCOUNT_TOO_LARGE: 422,
  DISCOUNT_LIMIT_EXCEEDED: 403,
  REASON_REQUIRED: 422,
  PACKAGE_NOT_ACTIVE: 422,
  PACKAGE_EXHAUSTED: 422,
  PACKAGE_EXPIRED: 422,
  PACKAGE_SERVICE_MISMATCH: 422,
  PACKAGE_SIZE_MISMATCH: 422,
  PACKAGE_PET_MISMATCH: 422,
  UPLOAD_KIND_NOT_ALLOWED: 422,
  UPLOAD_TYPE_NOT_ALLOWED: 422,
  UPLOAD_TOO_LARGE: 422,
  FILE_NOT_UPLOADED: 422,
  LINE_NOT_CONNECTED: 422,
  LINE_API_ERROR: 502,
  WEBHOOK_SIGNATURE_INVALID: 401,
  IMPORT_HAS_ERRORS: 422,
  CRON_FORBIDDEN: 401,
} as const satisfies Record<ErrorCode, number>;

export const ERROR_MESSAGE_TH = {
  UNAUTHENTICATED: "กรุณาเข้าสู่ระบบ",
  FORBIDDEN: "คุณไม่มีสิทธิ์ทำรายการนี้",
  SUPPORT_READ_ONLY: "โหมดช่วยเหลือดูข้อมูลได้อย่างเดียว",
  NOT_FOUND: "ไม่พบข้อมูล",
  VALIDATION_FAILED: "ข้อมูลไม่ถูกต้อง",
  INVALID_TRANSITION: "สถานะรายการเปลี่ยนไปแล้ว กรุณารีเฟรช",
  STALE_BILL: "บิลถูกแก้ไขจากอีกเครื่อง กรุณารีเฟรช",
  RATE_LIMITED: "ทำรายการถี่เกินไป กรุณารอสักครู่",
  INTERNAL: "ระบบขัดข้อง กรุณาลองใหม่",
  INVALID_CREDENTIALS: "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
  ACCOUNT_LOCKED: "บัญชีถูกล็อกชั่วคราว ลองใหม่ใน 15 นาที",
  PASSWORD_POLICY: "รหัสผ่านต้องยาว 8 ตัวขึ้นไป และไม่ใช่ตัวเลขล้วน",
  TOKEN_INVALID: "ลิงก์ไม่ถูกต้องหรือหมดอายุ",
  LINE_TOKEN_INVALID: "ยืนยันตัวตน LINE ไม่สำเร็จ กรุณาเปิดใหม่จาก LINE",
  NOT_REGISTERED: "กรุณาลงทะเบียนก่อนใช้งาน",
  LAST_OWNER: "ต้องมีเจ้าของร้านอย่างน้อย 1 คน",
  EMAIL_TAKEN: "อีเมลนี้ถูกใช้แล้ว",
  SLUG_TAKEN: "ชื่อลิงก์นี้ถูกใช้แล้ว",
  CODE_TAKEN: "รหัสนี้ถูกใช้แล้ว",
  IN_USE: "ใช้งานอยู่ ลบไม่ได้ — ให้ปิดใช้งานแทน",
  SIZE_TIER_OVERLAP: "ช่วงน้ำหนักทับกัน",
  INVALID_PHONE: "เบอร์โทรไม่ถูกต้อง",
  LINK_REQUEST_PENDING: "มีคำขอจับคู่บัญชีรอร้านยืนยันอยู่",
  MODULE_DISABLED: "ร้านยังไม่เปิดบริการนี้",
  BRANCH_CLOSED: "ร้านปิดในวันที่เลือก",
  OUTSIDE_BOOKING_WINDOW: "วันที่เลือกอยู่นอกช่วงที่จองได้",
  SLOT_TAKEN: "คิวนี้เพิ่งถูกจองไป กรุณาเลือกเวลาใหม่",
  ROOM_TAKEN: "ห้องเต็มในช่วงวันที่เลือก",
  PET_ALREADY_BOOKED: "น้องมีการจองที่ทับช่วงเวลานี้แล้ว",
  DAYCARE_FULL: "รอบ Daycare นี้เต็มแล้ว",
  PRICE_NOT_FOUND: "บริการนี้ไม่มีราคาสำหรับขนาด/ขนของน้อง",
  WEIGHT_REQUIRED: "กรุณาระบุน้ำหนักหรือขนาดของน้อง",
  DURATION_ZERO: "กรุณาเลือกบริการหลักอย่างน้อย 1 รายการ",
  INVALID_DATE_RANGE: "ช่วงวันที่ไม่ถูกต้อง",
  CUSTOMER_BLACKLISTED: "ไม่สามารถจองออนไลน์ได้ กรุณาติดต่อร้าน",
  PET_INACTIVE: "โปรไฟล์น้องไม่พร้อมใช้งาน",
  SPECIES_NOT_ALLOWED: "บริการนี้ไม่รองรับชนิดสัตว์ของน้อง",
  BREED_REJECTED: "ขออภัย ร้านยังไม่รับสายพันธุ์นี้",
  PET_TOO_HEAVY: "น้ำหนักน้องเกินที่ร้านรับได้",
  PET_TOO_YOUNG: "น้องอายุยังไม่ถึงเกณฑ์ของห้องนี้",
  IN_HEAT_NOT_ALLOWED: "ห้องนี้ไม่รับน้องที่อยู่ในช่วงติดสัด",
  REACTIVE_NOT_ALLOWED: "ห้องนี้ไม่รับน้องที่มีนิสัยก้าวร้าว",
  VACCINE_REQUIRED: "วัคซีนของน้องไม่ครบหรือหมดอายุ",
  STATUS_NOT_ALLOWED: "ทำรายการนี้ในสถานะปัจจุบันไม่ได้",
  TOO_LATE_TO_RESCHEDULE: "เลยเวลาที่เลื่อนนัดเองได้ กรุณาติดต่อร้าน",
  RESCHEDULE_LIMIT: "เลื่อนนัดครบจำนวนครั้งแล้ว กรุณาติดต่อร้าน",
  HOLD_EXPIRED: "หมดเวลาชำระมัดจำ คิวถูกปล่อยแล้ว",
  CONSENT_REQUIRED: "ต้องเซ็นใบยินยอมก่อน",
  INTAKE_INCOMPLETE: "กรอกฟอร์มรับฝากให้ครบก่อนเช็คอิน",
  PROMPTPAY_NOT_CONFIGURED: "ร้านยังไม่ได้ตั้งค่าบัญชี PromptPay",
  INVALID_PROMPTPAY_ID: "หมายเลข PromptPay ไม่ถูกต้อง",
  DUPLICATE_SLIP_CONFIRM_REQUIRED: "สลิปนี้เคยถูกใช้แล้ว ต้องยืนยันซ้ำอีกครั้ง",
  INVALID_AMOUNT: "จำนวนเงินไม่ถูกต้อง",
  AMOUNT_EXCEEDS_DUE: "ยอดเกินยอดค้างชำระ",
  INSUFFICIENT_CREDIT: "เครดิตคงเหลือไม่พอ",
  BILL_ALREADY_PAID: "บิลนี้ชำระครบแล้ว",
  BILL_HAS_DUE: "ยังมียอดค้างชำระ",
  BILL_NOT_OPEN: "บิลนี้ปิดหรือยกเลิกแล้ว",
  LINE_DISCOUNT_TOO_LARGE: "ส่วนลดเกินราคาสินค้า",
  BILL_DISCOUNT_TOO_LARGE: "ส่วนลดเกินยอดบิล",
  DISCOUNT_LIMIT_EXCEEDED: "ส่วนลดเกิน 20% ต้องให้เจ้าของร้านอนุมัติ",
  REASON_REQUIRED: "กรุณาระบุเหตุผล",
  PACKAGE_NOT_ACTIVE: "แพ็กเกจนี้ใช้ไม่ได้แล้ว",
  PACKAGE_EXHAUSTED: "แพ็กเกจนี้ใช้ครบแล้ว",
  PACKAGE_EXPIRED: "แพ็กเกจหมดอายุแล้ว",
  PACKAGE_SERVICE_MISMATCH: "แพ็กเกจนี้ใช้กับบริการนี้ไม่ได้",
  PACKAGE_SIZE_MISMATCH: "แพ็กเกจนี้ใช้กับขนาดนี้ไม่ได้",
  PACKAGE_PET_MISMATCH: "แพ็กเกจนี้เป็นของน้องตัวอื่น",
  UPLOAD_KIND_NOT_ALLOWED: "ไม่รองรับไฟล์ประเภทนี้",
  UPLOAD_TYPE_NOT_ALLOWED: "ไม่รองรับชนิดไฟล์นี้",
  UPLOAD_TOO_LARGE: "ไฟล์ใหญ่เกินกำหนด",
  FILE_NOT_UPLOADED: "อัปโหลดไฟล์ไม่สำเร็จ กรุณาลองใหม่",
  LINE_NOT_CONNECTED: "ร้านยังไม่ได้เชื่อม LINE OA",
  LINE_API_ERROR: "เชื่อมต่อ LINE ไม่สำเร็จ",
  WEBHOOK_SIGNATURE_INVALID: "invalid signature",
  IMPORT_HAS_ERRORS: "ไฟล์มีแถวที่ผิด กรุณาแก้แล้วอัปโหลดใหม่",
  CRON_FORBIDDEN: "forbidden",
} as const satisfies Record<ErrorCode, string>;
