#!/usr/bin/env python3
"""CI guard: generated files in the repo must equal what tools/spec-src produces right now.
  - docs/spec/02..10 + vectors + enum-labels  (exact)
  - docs/tasks/README.md, tasks.csv, tasks.json  (exact)
  - docs/tasks/<ID>.md  (exact above '## Status log' — agents may append to the log only)
Schema TS (packages/db/src/schema) is NOT compared — it is hand-maintained after day 0 and checked by `check:doc`."""
import filecmp, os, shutil, subprocess, sys, tempfile
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
tmp = tempfile.mkdtemp(prefix="spec-drift-")
env = dict(os.environ, TASK_IDS_READONLY="1", PYTHONDONTWRITEBYTECODE="1")
def run(script):
    r = subprocess.run([sys.executable, os.path.join(HERE, script), tmp], cwd=HERE, env=env, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout[-3000:], r.stderr[-3000:]); sys.exit(f"{script} failed")
os.makedirs(os.path.join(tmp, "packages/db/src/schema"), exist_ok=True)
for s in ("gen.py", "build_spec.py", "build_tasks.py"): run(s)
errors = []
def same(rel):
    a, b = os.path.join(REPO, rel), os.path.join(tmp, rel)
    if not os.path.exists(a): errors.append(f"missing in repo: {rel}")
    elif not filecmp.cmp(a, b, shallow=False): errors.append(f"differs from generated: {rel}")
gen_spec = os.path.join(tmp, "docs/spec")
for d, _, fs in os.walk(gen_spec):
    for f in fs: same(os.path.relpath(os.path.join(d, f), tmp))
for f in os.listdir(os.path.join(REPO, "docs/spec/vectors")):
    if not os.path.exists(os.path.join(gen_spec, "vectors", f)): errors.append(f"not generated (remove or add to spec-src): docs/spec/vectors/{f}")
cut = "## Status log"
for f in sorted(os.listdir(os.path.join(tmp, "docs/tasks"))):
    rel = f"docs/tasks/{f}"
    if not f.endswith(".md") or f == "README.md": same(rel); continue
    a = os.path.join(REPO, rel)
    if not os.path.exists(a): errors.append(f"missing in repo: {rel}"); continue
    mine, gen = open(a, encoding="utf-8").read(), open(os.path.join(tmp, rel), encoding="utf-8").read()
    if mine.split(cut)[0] != gen.split(cut)[0]: errors.append(f"card edited above '{cut}': {rel}")
for f in os.listdir(os.path.join(REPO, "docs/tasks")):
    if not os.path.exists(os.path.join(tmp, "docs/tasks", f)): errors.append(f"card not generated by spec-src: docs/tasks/{f}")
shutil.rmtree(tmp)
if errors:
    print("SPEC DRIFT — generated files were edited by hand or spec-src changed without regenerating:")
    for e in errors[:100]: print("  -", e)
    print("Fix: edit tools/spec-src/*.py, then run gen.py / build_spec.py / build_tasks.py and commit the result (PR label spec-change).")
    sys.exit(1)
print("spec drift: OK")
