# -*- coding: utf-8 -*-
"""
Screen specs. Field tuple: (mode, label, source, ui, rule)
  mode: R = แสดงอย่างเดียว, W = กรอกใหม่, E = แสดงค่าเดิมและแก้ได้, F = ตัวกรอง/ค้นหา (ไม่บันทึก)
  source: table.column | calc:... (ต้องอ้าง R-xx หรืออธิบายสูตร)
  ui: ชนิด control / รูปแบบแสดงผล (money = R-31 formatTHB, date = formatThaiDate, time = formatTime, phone = R-22 formatPhone,
      weight = R-31 formatWeight, enum = ป้ายภาษาไทยจาก enum label, badge = ป้ายสี)
Action tuple: (label, endpoint key, when visible/enabled, after success)
"""
SCR = []

def scr(id, app, route, title, roles, stories, purpose, load, sections, actions=None, notes=None):
    SCR.append(dict(id=id, app=app, route=route, title=title, roles=roles, stories=stories, purpose=purpose, load=load,
                    sections=sections, actions=actions or [], notes=notes or []))

def R(label, src, ui="text", rule=""): return ("R", label, src, ui, rule)
def W(label, src, ui, rule=""): return ("W", label, src, ui, rule)
def E(label, src, ui, rule=""): return ("E", label, src, ui, rule)
def Q(label, src, ui, rule=""): return ("F", label, src, ui, rule)

# ====================================================================== AUTH / PUBLIC
scr("A-01", "auth", "/login", "เข้าสู่ระบบ (ร้าน)", "public", "US-01-02", "พนักงานเข้าสู่ระบบด้วยอีเมล หรือปุ่ม LINE (สำหรับช่าง)", [],
    [("ฟอร์ม", [W("อีเมล", "staff_user.email", "email input, autocomplete=username", "บังคับ, trim+lowercase"),
                W("รหัสผ่าน", "staff_user.password_hash", "password input + ปุ่มแสดงรหัส", "บังคับ")])],
    [("เข้าสู่ระบบ", "auth.staffLogin", "ฟอร์มครบ", "→ /console (owner/front_desk) หรือ /staff (staff)"),
     ("เข้าด้วย LINE", "auth.staffLine", "เสมอ", "LINE Login ของแพลตฟอร์ม → /staff"),
     ("ลืมรหัสผ่าน", "—", "", "→ /forgot-password")],
    ["error INVALID_CREDENTIALS / ACCOUNT_LOCKED แสดงใต้ฟอร์ม (ไม่ล้างอีเมล)"])
scr("A-02", "auth", "/forgot-password", "ลืมรหัสผ่าน", "public", "US-01-02", "ขอลิงก์รีเซ็ต", [],
    [("ฟอร์ม", [W("อีเมล", "staff_user.email", "email input", "บังคับ")])],
    [("ส่งลิงก์", "auth.resetRequest", "", "แสดงข้อความเดียวกันเสมอ 'ถ้ามีบัญชีนี้ เราได้ส่งลิงก์ไปแล้ว'")])
scr("A-03", "auth", "/reset-password?token=", "ตั้งรหัสผ่านใหม่", "public", "US-01-02", "ตั้งรหัสใหม่จากลิงก์", [],
    [("ฟอร์ม", [W("รหัสผ่านใหม่", "staff_user.password_hash", "password + ตัวชี้ความแข็งแรง", "R-24"),
                W("ยืนยันรหัสผ่าน", "calc: ต้องตรงกับช่องแรก (ไม่ส่ง server)", "password", "ตรงกัน")])],
    [("บันทึก", "auth.resetConfirm", "", "→ /login พร้อม toast 'ตั้งรหัสผ่านแล้ว'")])
scr("A-04", "auth", "/invite/[token]", "รับคำเชิญเข้าร้าน", "public", "US-01-04", "พนักงานใหม่ตั้งชื่อ/รหัส หรือผูก LINE", [],
    [("ข้อมูลร้าน", [R("ชื่อร้าน", "organization.name"), R("ตำแหน่ง", "staff_user.role", "enum")]),
     ("ฟอร์ม", [E("ชื่อเล่นที่ลูกค้าเห็น", "staff_user.display_name", "text", "1–40 บังคับ"),
                W("อีเมล", "staff_user.email", "email", "แสดงเมื่อคำเชิญไม่มีอีเมล"),
                W("รหัสผ่าน", "staff_user.password_hash", "password", "R-24; ไม่บังคับถ้ากดใช้ LINE")])],
    [("เริ่มใช้งาน", "auth.inviteAccept", "", "→ /console หรือ /staff ตาม role"),
     ("ใช้ LINE แทนรหัสผ่าน", "auth.inviteAccept + staffMe.linkLine", "", "→ /staff")],
    ["owner รับคำเชิญครั้งแรก: แสดงเงื่อนไขการใช้บริการ + DPA ให้กดยอมรับ (insert consent_record subject organization)"])
scr("P-01", "public", "/b/[bookingSlug]", "หน้าลิงก์จองของร้าน", "public", "US-02-07", "หน้าเว็บสาธารณะจาก QR โปสเตอร์ — พาไปจองใน LINE", ["public.branch"],
    [("หัวร้าน", [R("โลโก้", "branch.logo_file_id", "image 96px"), R("ชื่อร้าน", "branch.name", "h1"), R("ที่อยู่", "branch.address_line", "text + ลิงก์แผนที่"),
                  R("เบอร์โทร", "branch.phone", "phone + tel: link"), R("เวลาเปิด", "branch_hours.opens_at", "ตาราง 7 วัน 'จ. 09:00–18:00' / 'ปิด'")]),
     ("บริการ", [R("ชื่อบริการ", "service.name_th"), R("ราคาเริ่มต้น", "calc: min(service_price.price_satang)", "money 'เริ่ม ฿350'"),
                 R("ประเภทห้อง", "room_type.name_th"), R("ราคาต่อคืนเริ่ม", "calc: min(room_rate.nightly_price_satang)", "money")])],
    [("จองผ่าน LINE", "—", "line_channel.status = active", "เปิด liffUrl"), ("เพิ่มเพื่อน", "—", "มี bot_basic_id", "เปิด addFriendUrl")],
    ["ไม่มี LINE เชื่อม → ซ่อนปุ่มจอง แสดงปุ่มโทร", "SEO: title = ชื่อร้าน + จังหวัด, OG image = โลโก้"])
scr("P-02", "public", "/legal/[doc]", "เอกสารกฎหมาย", "public", "US-13-08", "แสดง Privacy Notice / Terms / DPA ฉบับปัจจุบัน (ลิงก์จาก L-01, L-15, A-04)", [],
    [("เอกสาร", [R("ชื่อเอกสาร", "calc: LEGAL_DOCS[doc]", "h1 ตาม enum legal_doc"), R("ฉบับ", "calc: LEGAL_DOCS[doc].version (ค่าเดียวกับ consent_record.version ที่บันทึกตอนยอมรับ)", "'ฉบับวันที่ 1 ต.ค. 2569' (version จาก 10-reference-data)"),
                 R("เนื้อหา", "calc: ไฟล์ markdown ใน LEGAL_DOCS[doc].file", "markdown → HTML (static, build time)")])],
    [], ["doc ∈ privacy | terms | dpa (ตาม route ใน 10-reference-data); อื่น ๆ → 404", "หน้า static ไม่เรียก API — อ่านไฟล์ตอน build"])

# ====================================================================== CONSOLE
scr("C-01", "console", "/console", "วันนี้ (Dashboard)", "OF", "US-12-01", "ภาพรวมวันนี้ + สิ่งที่ต้องทำ", ["dashboard.today"],
    [("การ์ดตัวเลข", [R("กรูมวันนี้", "calc: DashboardToday.groom.total", "number + แยกสถานะ (badge)"),
                      R("เข้า/ออก/พักอยู่", "calc: DashboardToday.hotel.*", "3 ตัวเลข"), R("Occupancy", "calc: DashboardToday.hotel.occupancyPercent", "percent 0 ตำแหน่ง"),
                      R("Daycare", "calc: DashboardToday.daycare.count", "number"),
                      R("ยอดรับเงินวันนี้", "calc: DashboardToday.sales.paidTotalSatang", "money", "owner เท่านั้น")]),
     ("ต้องทำ (กดแล้วไปหน้าที่เกี่ยวข้อง)", [R("สลิปรอตรวจ", "calc: count payment_slip submitted", "badge แดงถ้า > 0 → C-07"),
        R("รออนุมัติ", "calc: count booking awaiting_approval", "badge → C-04 tab"), R("งานดูแลเลยเวลา", "calc: care_task overdue", "badge → C-16"),
        R("Report card รอตรวจ", "calc: report_card pending_review", "→ C-21"), R("ข้อความไม่ได้ส่ง", "calc: notification skipped วันนี้", "→ C-22"),
        R("รับน้องแล้วยังไม่ปิดบิล", "calc: DashboardToday.todo.pickupsWithoutBill", "→ C-19"), R("คำขอจับคู่ LINE", "calc: customer_link_request pending", "→ C-12")]),
     ("คิวถัดไป", [R("เวลา", "groom_appointment.starts_at", "time"), R("น้อง", "pet.name", "ชื่อ + ป้ายนิสัย"), R("ช่าง", "staff_user.display_name"),
                   R("สถานะ", "groom_appointment.status", "enum badge")])],
    [("+ จองใหม่", "—", "", "→ C-03")], ["รีเฟรชอัตโนมัติทุก 60 วินาที และเมื่อได้ web push"])
scr("C-02", "console", "/console/calendar?date=&view=day|week", "ปฏิทินคิว", "OFS", "US-05-03", "ตารางคิวกรูมรายวัน (คอลัมน์ = ช่าง) ลากเพื่อย้ายเวลา/ช่าง", ["calendar.day"],
    [("แถบบน", [Q("วันที่", "calc: query date", "date picker + ปุ่มวันนี้/←/→"), Q("มุมมอง", "calc: view", "segmented วัน/สัปดาห์"),
                Q("ช่าง", "groom_appointment.groomer_id", "select (ทุกคน)"), R("ปิดร้าน/ปิดบางช่วง", "branch_closure.starts_at", "แถบเทาทับช่วงเวลา + เหตุผล")]),
     ("การ์ดนัด (ในตาราง)", [R("เวลา", "groom_appointment.starts_at", "time–time (ends_at)"), R("ช่วง buffer", "groom_appointment.blocked_until", "แถบลาย"),
        R("ชื่อน้อง", "pet.name", "ตัวหนา"), R("พันธุ์/ขนาด", "pet.breed", "เล็ก + size_tier.code"), R("ป้ายนิสัย", "pet_temperament_flag.flag", "ไอคอน 🦷 กัด ฯลฯ"),
        R("บริการ", "groom_appointment_item.name_snapshot", "ย่อ 1 บรรทัด"), R("สถานะ", "groom_appointment.status", "สีการ์ด"),
        R("มัดจำ", "booking.deposit_status", "ไอคอน ✓/รอ"), R("ระดับลูกค้า", "customer.reliability_level", "จุดสี 1 แดง 2 ส้ม 4 ทอง"),
        R("โต๊ะ", "groom_station.name", "เล็กมุมล่าง"), R("เบอร์ลูกค้า", "owner_profile.phone_e164", "phone", "ซ่อนจาก role staff")]),
     ("แถบข้าง", [R("Hotel วันนี้", "calc: CalendarDay.hotel.*", "เข้า/ออก/พัก"), R("Daycare", "calc: CalendarDay.daycare.count", ""),
                  R("ช่วงพัก/ลาของช่าง", "staff_time_off.starts_at", "แถบเทา")])],
    [("ลากการ์ดไปเวลา/ช่างใหม่", "groom.reschedule", "OF, status scheduled", "ยืนยัน dialog 'แจ้งลูกค้าไหม' → รีโหลด; SLOT_TAKEN → การ์ดเด้งกลับ + toast"),
     ("คลิกช่องว่าง", "—", "OF", "เปิด C-03 พร้อมวัน/เวลา/ช่าง"), ("คลิกการ์ด", "—", "", "เปิด C-02D (drawer รายละเอียดนัด)")],
    ["ช่วงเวลาแกน Y = เวลาเปิด–ปิดของวัน ทีละ slot_step", "role staff: อ่านอย่างเดียว ลากไม่ได้"])
scr("C-02D", "console", "(drawer บน C-02 / C-05 / C-01)", "รายละเอียดนัดกรูม (drawer)", "OFS", "US-05-03, US-05-08, US-05-09, US-07-07, US-04-05",
    "ดูนัดเดียวแบบเร็วและกดเปลี่ยนสถานะ โดยไม่ออกจากปฏิทิน", ["groom.jobCard"],
    [("หัว", [R("เวลา", "groom_appointment.starts_at", "date + time–time (ends_at)"), R("สถานะ", "groom_appointment.status", "enum badge ใหญ่"),
              R("เลขใบจอง", "booking.booking_no", "mono ลิงก์ → C-05"), R("ช่าง", "staff_user.display_name", "+ ป้าย 'ลูกค้าเลือก' ถ้า groomer_preference = requested"),
              R("โต๊ะ", "groom_station.name", "")]),
     ("น้องและเจ้าของ", [R("น้อง", "pet.name", "รูป + ชื่อ + พันธุ์ + size_tier.code → ลิงก์ C-11"), R("ป้ายนิสัย", "pet_temperament_flag.flag", "แถบแดง"),
              R("แพ้/ห้ามใช้", "pet_shop_profile.allergies", "แดง + shampoo_avoid"), R("เจ้าของ", "owner_profile.first_name", "ลิงก์ → C-09"),
              R("เบอร์", "owner_profile.phone_e164", "phone + ปุ่มโทร", "ซ่อนจาก role staff"), R("ระดับลูกค้า", "customer.reliability_level", "badge (R-09)"),
              R("มัดจำ", "booking.deposit_status", "enum badge")]),
     ("บริการ", [R("รายการ", "groom_appointment_item.name_snapshot", "แถว: ชื่อ + (add-on) + duration_minutes + money (price_satang); ใช้แพ็กเกจ → ป้าย 'แพ็กเกจ'"),
                 R("ค่าบริการเพิ่ม", "appointment_surcharge.name", "แถว: ชื่อ + money (amount_satang) + reason + ปุ่มลบ (OF)"),
                 R("รวมบริการ", "groom_appointment.services_total_satang", "money"), R("รวมค่าเพิ่ม", "groom_appointment.surcharge_total_satang", "money")]),
     ("หน้างาน", [R("เช็คอินเมื่อ", "groom_appointment.checked_in_at", "time"), R("น้ำหนักวันนี้", "groom_appointment.weight_grams_checkin", "weight"),
                  R("สภาพที่พบ", "groom_appointment.condition_flags", "ป้าย + condition_note"), R("ใบยินยอม", "calc: JobCard.consentSigned", "✓ เซ็นแล้ว / —"),
                  R("เสร็จเมื่อ", "groom_appointment.done_at", "time"), R("โน้ตช่าง", "groom_appointment.staff_note", ""), R("โน้ตลูกค้า", "booking.customer_note", "quote")]),
     ("ค่าบริการเพิ่ม (dialog)", [W("ประเภท", "appointment_surcharge.surcharge_type_id", "select surcharge_type active (prefill ชื่อ + default_amount_satang)", "บังคับ"),
                  W("ชื่อที่แสดงในบิล", "appointment_surcharge.name", "text", "1–60"), W("ยอด", "appointment_surcharge.amount_satang", "money input", "> 0"),
                  W("เหตุผล", "appointment_surcharge.reason", "text (ลูกค้าเห็นในบิล)", "≤ 200")])],
    [("เช็คอิน", "groom.checkIn", "OF, status scheduled, วันนี้", "เปิด dialog C-06"),
     ("เริ่มงาน", "groom.start", "status checked_in", "การ์ดเปลี่ยนสี in_progress"),
     ("เสร็จงาน", "groom.finish", "status in_progress", "สร้าง report card draft → ช่างกรอกที่ S-03"),
     ("แจ้งลูกค้ามารับ", "groom.notifyPickup", "OF, status done", "ส่ง LINE ข้อความ 'พร้อมรับ' (notification ready_for_pickup, นับโควตา R-18; dedupe ต่อนัด — กดซ้ำไม่ส่งซ้ำ) แล้ว toast 'แจ้งลูกค้าแล้ว'"),
     ("ลูกค้ารับน้องแล้ว", "groom.pickUp", "OF, status done", "ถ้ายังไม่มีบิล → ปุ่ม 'เปิดบิล' (bills.open) → C-18"),
     ("ลูกค้าไม่มา", "groom.noShow", "OF, status scheduled, now ≥ starts_at + branch_policy.no_show_grace_minutes", "dialog เหตุผล + แสดงผลมัดจำ (R-07) และผลต่อระดับลูกค้า (R-09) ก่อนยืนยัน"),
     ("ยกเลิกนัดตัวนี้", "groom.cancel", "OF, status scheduled|checked_in", "dialog เหตุผล (ยกเลิกทั้งใบ → ไป C-05)"),
     ("ค่าบริการเพิ่มหน้างาน", "groom.addSurcharge / groom.removeSurcharge", "OF, status checked_in|in_progress|done และบิลยังไม่ปิด", "dialog: ประเภท (surcharge_type) + ยอด + เหตุผล; ลบได้จนกว่าบิลปิด")],
    ["ปุ่มแสดงตาม state machine groom_appointment (03) และ role — ไม่ซ่อนด้วยเงื่อนไขอื่นที่ไม่อยู่ในตารางนี้", "หลังทุก action สำเร็จ: ปิด/คงเปิด drawer ตามที่ระบุ แล้ว invalidate calendar.day + bookings.get"])
scr("C-03", "console", "/console/bookings/new", "สร้างใบจอง (หน้าร้าน)", "OF", "US-05-04, US-06-03, US-06-07, US-06-13", "ลงนัดให้ลูกค้าที่โทร/ทักแชท/walk-in",
    ["search.quick", "availability.groomSlots", "availability.hotel", "availability.daycare", "quotes.create"],
    [("1. ลูกค้า", [Q("ค้นหาลูกค้า", "owner_profile.phone_e164", "search box (ชื่อ/เบอร์/ชื่อน้อง)", "R-22 สำหรับเบอร์"),
                    R("ลูกค้าที่เลือก", "owner_profile.first_name", "ชื่อ + เบอร์ + badge ระดับ (R-09) + blacklisted แดง"),
                    W("ช่องทาง", "booking.channel", "segmented walk_in/phone/chat", "บังคับ")]),
     ("2. บริการ (เลือกได้หลายแท็บ)", [
        W("น้อง", "groom_appointment.pet_id", "chips น้องของลูกค้า (หลายตัวได้)", "pet.status active"),
        W("บริการหลัก", "groom_appointment_item.service_id", "รายการ + ราคาตามขนาด/ขน (R-02)", "≥ 1"),
        W("Add-on", "groom_appointment_item.service_id", "checkbox (เฉพาะที่ link กับบริการหลัก)", ""),
        W("ขนาด (ถ้าไม่รู้น้ำหนัก)", "groom_appointment.size_tier_id", "select", "แสดงเมื่อ R-01 = no_weight"),
        W("ใช้แพ็กเกจ", "groom_appointment_item.customer_package_id", "select แพ็กเกจที่ R-14 canRedeem = ok", ""),
        W("ช่าง", "groom_appointment.groomer_id", "select ใครก็ได้/ระบุ", ""), W("วันที่", "calc: date", "date picker", ""),
        W("เวลา", "groom_appointment.starts_at", "grid ปุ่ม slot (R-04) แสดงชื่อช่างที่ระบบเลือก", "ต้องเลือกจากผล"),
        W("Hotel: ประเภทห้อง", "stay.room_type_id", "การ์ดประเภท + ห้องว่าง (R-28) + ราคา/คืน", ""), W("เช็คอิน–เช็คเอาท์", "stay.check_in_date", "date range", "≤ 30 คืน"),
        W("เวลาที่จะมา/รับ", "stay.expected_check_in_time", "time select", ""), W("ห้อง (ไม่บังคับ)", "stay.room_unit_id", "select ห้องว่าง; ไม่เลือก = ระบบจัดห้องให้อัตโนมัติ (R-10)", "ต้องว่างทุกคืน (R-10)"),
        W("ติดสัด", "stay.in_heat", "toggle", "เพศเมีย"), W("Add-on ระหว่างพัก", "stay_addon.service_id", "checkbox", ""),
        W("อาบน้ำก่อนกลับ", "stay.bundle_appointment_id", "toggle → เลือกบริการ + slot วันเช็คเอาท์", "US-06-07"),
        W("Daycare: วัน", "daycare_visit.visit_date", "date", ""), W("รอบ", "daycare_visit.session_type_id", "segmented + ที่ว่าง (R-29)", "")]),
     ("3. สรุป", [R("รายการและราคา", "calc: Quote", "ตาราง money"), R("ยอดประเมิน", "booking.estimated_total_satang", "money ตัวใหญ่"),
                  R("มัดจำที่แนะนำ", "booking.deposit_required_satang", "money + เหตุผล (R-06)"),
                  E("ปรับมัดจำ", "booking.deposit_required_satang", "money input", "เหตุผลบังคับเมื่อแก้"),
                  W("โน้ตจากลูกค้า", "booking.customer_note", "textarea", "≤ 500"),
                  R("คำเตือน", "calc: R-11/R-12 warnings", "กล่องเหลือง (วัคซีนไม่ครบ ฯลฯ) — ไม่บล็อก")])],
    [("บันทึกการจอง", "bookings.create", "สรุปถูกต้อง", "→ C-05 + toast เลขใบจอง; SLOT_TAKEN → กลับขั้นเลือกเวลา")],
    ["ถ้าลูกค้าใหม่: ปุ่ม 'เพิ่มลูกค้า' เปิด C-10 แบบ dialog แล้วกลับมาขั้นตอนเดิม"])
scr("C-04", "console", "/console/bookings?tab=approval|deposit|upcoming|all", "ใบจอง", "OF", "US-05-05, US-07-03", "คิวงานอนุมัติ/ตามมัดจำ", ["bookings.list"],
    [("แท็บ", [Q("รออนุมัติ", "booking.status", "tab + จำนวน", "awaiting_approval"), Q("รอมัดจำ", "booking.status", "tab", "awaiting_deposit, deposit_review"),
               Q("กำลังจะมา", "booking.status", "tab", "confirmed, first_service_at ≥ วันนี้"), Q("ทั้งหมด", "booking.status", "tab + filter สถานะ/วันที่", "")]),
     ("ตาราง", [R("เลขใบจอง", "booking.booking_no", "mono"), R("ลูกค้า", "owner_profile.first_name", "ชื่อ + ระดับ"), R("น้อง", "pet.name", "chips"),
                R("บริการ", "calc: modules", "ไอคอน ✂️/🏨/🌞"), R("วันเวลาเริ่ม", "booking.first_service_at", "date + time"),
                R("ยอด", "booking.estimated_total_satang", "money"), R("มัดจำ", "booking.deposit_status", "enum badge + ยอด"),
                R("หมดเวลา", "booking.hold_expires_at", "นับถอยหลัง mm:ss (awaiting_deposit)"), R("อนุมัติภายใน", "booking.approval_due_at", "นับถอยหลัง, แดงเมื่อเลย"),
                R("ช่องทาง", "booking.channel", "enum")])],
    [("อนุมัติ", "bookings.approve", "awaiting_approval", "แถวหายจากแท็บ"), ("ปฏิเสธ", "bookings.decline", "awaiting_approval", "dialog เหตุผล (ลูกค้าเห็น)")])
scr("C-05", "console", "/console/bookings/[bookingId]", "รายละเอียดใบจอง", "OF", "US-05-04, US-05-08, US-07-02..05, US-07-08", "จัดการใบจองทั้งใบ", ["bookings.get"],
    [("หัว", [R("เลขใบจอง", "booking.booking_no", "h1 mono"), R("สถานะ", "booking.status", "enum badge ใหญ่"), R("ช่องทาง", "booking.channel", "enum"),
              R("สร้างเมื่อ", "booking.created_at", "date time"), R("ลูกค้า", "owner_profile.first_name", "ลิงก์ → C-09 + เบอร์ + ระดับ")]),
     ("บริการ", [R("นัดกรูม", "groom_appointment.starts_at", "การ์ด AppointmentCard ต่อน้อง + ปุ่มตามสถานะ"),
                 R("การพัก", "stay.check_in_date", "การ์ด StayCard → C-15"), R("Daycare", "daycare_visit.visit_date", "แถว + สถานะ")]),
     ("เงิน", [R("ยอดประเมิน", "booking.estimated_total_satang", "money"), R("มัดจำที่ต้องจ่าย", "booking.deposit_required_satang", "money"),
               R("มัดจำที่ยืนยันแล้ว", "booking.deposit_verified_satang", "money"), R("สถานะมัดจำ", "booking.deposit_status", "enum badge"),
               R("สลิป", "payment_slip.file_id", "thumbnail → C-07 dialog"), R("บิล", "booking.bill_id", "ลิงก์ → C-18")]),
     ("นโยบาย ณ เวลาจอง", [R("ยกเลิกฟรีก่อน", "booking.policy_snapshot", "'กรูม 24 ชม. / โรงแรม 72 ชม. / ริบ 100%'")]),
     ("ประวัติ", [R("เหตุการณ์", "booking_event.to_status", "timeline: เวลา + จาก→ไป + ผู้ทำ + เหตุผล")]),
     ("โน้ต", [R("โน้ตจากลูกค้า", "booking.customer_note", "quote")])],
    [("อนุมัติ/ปฏิเสธ", "bookings.approve / bookings.decline", "awaiting_approval", ""),
     ("รับมัดจำ", "bookings.recordDeposit", "deposit pending/rejected", "dialog: วิธี, ยอด, เลขอ้างอิง, รูปหลักฐาน"),
     ("ยกเว้นมัดจำ", "bookings.waiveDeposit", "deposit pending", "dialog เหตุผล"),
     ("ยกเลิกใบจอง", "bookings.cancelPreview → bookings.cancel", "status active", "dialog: ใครยกเลิก (ลูกค้าขอ/ร้าน), แสดงผลเงิน R-07 ก่อนยืนยัน, ช่องเหตุผล"),
     ("เปิดบิล", "bills.open", "confirmed และมี child เสร็จแล้ว", "→ C-18"), ("ส่งลิงก์จ่ายยอดคงเหลือ", "bookings.balanceLink", "มีบิล open", "copy link / ส่ง LINE"),
     ("คลิกการ์ดนัดกรูม", "—", "", "เปิด C-02D (ปุ่มเช็คอิน/ไม่มา/ยกเลิก/ค่าเพิ่ม อยู่ใน drawer)"),
     ("ยกเลิกการพักตัวนี้", "stays.cancel", "stay reserved", "dialog เหตุผล"),
     ("ยกเลิก Daycare วันนี้", "daycare.cancel", "daycare_visit reserved", "dialog เหตุผล")])
scr("C-06", "console", "(dialog บน C-02/C-05)", "เช็คอินกรูม", "OF", "US-05-06", "รับน้องเข้าร้าน + ใบยินยอม", ["groom.jobCard"],
    [("น้อง", [R("ชื่อ/พันธุ์/ป้ายนิสัย", "pet.name", "header"), R("น้ำหนักล่าสุด", "pet.latest_weight_grams", "weight"),
               R("บริการที่จอง", "groom_appointment_item.name_snapshot", "list + ราคา")]),
     ("ตรวจรับ", [W("น้ำหนักวันนี้ (กก.)", "groom_appointment.weight_grams_checkin", "number 0.1 กก. → แปลงเป็นกรัม", "0.1–150"),
                  W("สภาพที่พบ", "groom_appointment.condition_flags", "checkbox: เห็บหมัด / แผล / ขนพันกัน / ผิวหนังมีปัญหา", ""),
                  W("รายละเอียด", "groom_appointment.condition_note", "textarea", "≤ 500")]),
     ("ใบยินยอม (แสดงเมื่อเลือก ขนพันกัน/ผิวหนัง หรือกดเพิ่มเอง)", [
        W("เหตุผล", "consent_document.reasons", "checkbox: ต้องไถขน / สูงวัย / โรคประจำตัว / ดุ / อื่นๆ", "≥ 1"),
        R("ข้อความใบยินยอม", "branch_policy.grooming_consent_text", "กล่องข้อความเลื่อนอ่านได้"),
        W("ชื่อผู้เซ็น", "consent_document.signer_name", "text", "บังคับ"),
        W("ลายเซ็น", "consent_document.signature_file_id", "signature pad (canvas → PNG อัปโหลด kind signature)", "บังคับ")])],
    [("เช็คอิน", "groom.checkIn", "", "ปิด dialog; ถ้า response.warnings มี SIZE_CHANGED → dialog 'ขนาดเปลี่ยนเป็น X ราคาใหม่ ฿xxx ปรับไหม'"),
     ("ปรับบริการ/ขนาดตามน้ำหนักวันนี้", "groom.setItems", "หลังเช็คอิน และผู้ใช้กดยืนยันใน dialog ราคาใหม่", "อัปเดตรายการ + ราคา (R-02/R-03)")])
scr("C-07", "console", "/console/slips", "สลิปรอตรวจ", "OF", "US-07-02", "ตรวจสลิปที่ลูกค้าส่ง (ร้านต้องเช็คยอดเข้าบัญชีจริงก่อนกดยืนยัน)", ["slips.list"],
    [("รายการ (เรียงเก่า→ใหม่)", [R("รูปสลิป", "payment_slip.file_id", "thumbnail คลิกขยาย"), R("ใบจอง", "booking.booking_no", "ลิงก์"),
        R("ลูกค้า", "owner_profile.first_name"), R("ยอดที่ต้องจ่าย", "payment_slip.amount_expected_satang", "money"),
        R("เลขอ้างอิงสลิป", "payment_slip.trans_ref", "mono, '-' ถ้าอ่าน QR ไม่ได้"),
        R("สลิปซ้ำ", "payment_slip.duplicate_of_slip_id", "badge แดง 'เคยใช้แล้ว' + ลิงก์สลิปเดิม"), R("ส่งเมื่อ", "payment_slip.created_at", "time ago"),
        R("คิวถูกกันถึง", "booking.hold_expires_at", "แสดงเมื่อมีค่า")]),
     ("ยืนยัน", [E("ยอดที่เข้าจริง", "payment.amount_satang", "money input (prefill = ยอดที่ต้องจ่าย)", "> 0")])],
    [("ยืนยัน (เงินเข้าแล้ว)", "slips.verify", "submitted", "สลิปซ้ำ → dialog ยืนยันชั้นที่ 2 (confirmDuplicate)"),
     ("ยืนยัน + อนุมัติจอง", "slips.verify (approveBooking=true)", "booking ต้องอนุมัติ", ""),
     ("ปฏิเสธ", "slips.reject", "submitted", "dialog เหตุผล (ลูกค้าเห็น)")])
scr("C-08", "console", "/console/customers", "ลูกค้า", "OF", "US-03-01, US-03-10", "ค้นหา/ดูลูกค้าทั้งหมด", ["customers.list"],
    [("ค้นหา", [Q("ค้นหา", "owner_profile.first_name", "search (ชื่อ ชื่อเล่น เบอร์ ชื่อน้อง)", "debounce 300ms, ≥ 2 ตัว"),
                Q("เรียง", "customer.last_visit_at", "select ล่าสุด/ชื่อ/ใหม่", "")]),
     ("ตาราง", [R("ชื่อ", "owner_profile.first_name", "ชื่อ + (ชื่อเล่น)"), R("เบอร์", "owner_profile.phone_e164", "phone"),
                R("น้อง", "pet.name", "chips + ไอคอนชนิด"), R("มาล่าสุด", "customer.last_visit_at", "date"), R("จำนวนครั้ง", "customer.visit_count", "number"),
                R("ระดับ", "customer.reliability_level", "badge (override ถ้ามี)"), R("เครดิต", "customer.credit_balance_satang", "money ซ่อนถ้า 0"),
                R("LINE", "calc: มี line_identity", "ไอคอน LINE")])],
    [("+ เพิ่มลูกค้า", "—", "", "→ C-10"), ("คลิกแถว", "—", "", "→ C-09")])
scr("C-09", "console", "/console/customers/[customerId]?tab=info|pets|timeline|packages|credit", "ลูกค้า", "OF",
    "US-03-01, US-03-08, US-03-09, US-07-05, US-10-05", "ข้อมูลลูกค้าครบในหน้าเดียว", ["customers.get", "customers.timeline", "customers.packages"],
    [("หัว", [R("ชื่อ", "owner_profile.first_name", "h1 ชื่อ นามสกุล (ชื่อเล่น)"), R("เบอร์", "owner_profile.phone_e164", "phone + ปุ่มโทร"),
              R("LINE", "line_identity.display_name", "รูป + ชื่อ + 'เป็นเพื่อน/ยังไม่เป็นเพื่อน'"), R("ระดับ", "customer.reliability_level", "badge + tooltip ที่มา (R-09)"),
              R("Blacklist", "customer.blacklisted", "แถบแดง + เหตุผล"), R("เครดิต", "customer.credit_balance_satang", "money")]),
     ("แท็บข้อมูล", [R("อีเมล", "owner_profile.email"), R("วันเกิด", "owner_profile.birth_date", "date"), R("ที่อยู่", "owner_profile.address_line", "รวม ตำบล อำเภอ จังหวัด รหัส"),
        R("ผู้ติดต่อฉุกเฉิน", "customer.emergency_contact_name", "ชื่อ + phone"), R("รู้จักร้านจาก", "customer.source_channel", "enum + referral_note"),
        R("ยินยอมใช้รูป", "customer.photo_consent", "enum badge"), R("ยกเว้นมัดจำ", "customer.deposit_exempt", "ใช่/ไม่"),
        R("โน้ตภายใน", "customer.internal_note", "กล่องเหลือง 'ลูกค้าไม่เห็น'"), R("ยกเลิกกระชั้น/ไม่มา 12 เดือน", "customer.late_cancel_count_12m", "x / y (no_show_count_12m)"),
        R("มาครั้งแรก/ล่าสุด", "customer.first_visit_at", "date / date (last_visit_at)")]),
     ("แท็บน้อง", [R("การ์ดน้อง", "pet.name", "รูป + ชื่อ + พันธุ์ + อายุ (R-12) + น้ำหนัก + ป้าย + สถานะวัคซีน → C-11")]),
     ("แท็บประวัติ", [R("รายการ", "calc: customers.timeline", "timeline ไอคอนตามประเภท + จำนวนเงิน")]),
     ("แท็บแพ็กเกจ", [R("แพ็กเกจ", "customer_package.status", "ชื่อ + น้อง + เหลือ x/y + หมดอายุ (date)"),
                       R("ประวัติการใช้สิทธิ์", "package_redemption.redeemed_at", "แถวย่อย: วันที่ + น้อง + ช่าง + เลขใบเสร็จ; reversed_at มีค่า → ขีดฆ่า 'ยกเลิก (void บิล)'")]),
     ("แท็บเครดิต", [R("ยอดคงเหลือ", "customer.credit_balance_satang", "money"), R("ประวัติ", "credit_ledger.delta_satang", "ตาราง: เวลา, +/−money, เหตุผล (enum), อ้างอิง")])],
    [("แก้ไข", "—", "", "→ C-10"), ("+ เพิ่มน้อง", "pets.create", "", "dialog ฟอร์มน้อง (ฟิลด์เดียวกับ C-11 แท็บโปรไฟล์)"),
     ("จองให้ลูกค้านี้", "—", "", "→ C-03 พร้อมลูกค้า"), ("Blacklist", "customers.blacklist", "owner", "dialog เหตุผล"),
     ("กำหนดระดับเอง", "customers.reliabilityOverride", "owner", "dialog 1–4/อัตโนมัติ + เหตุผล"),
     ("ปรับเครดิต", "customers.credit", "owner", "dialog +/− ยอด + เหตุผล"), ("บันทึกคืนเงิน", "refunds.create", "OF", "dialog")])
scr("C-10", "console", "/console/customers/new | /console/customers/[customerId]/edit", "ฟอร์มลูกค้า", "OF", "US-03-01", "เพิ่ม/แก้ลูกค้า", ["customers.get"],
    [("ข้อมูลหลัก", [E("ชื่อ", "owner_profile.first_name", "text", "บังคับ 1–60"), E("นามสกุล", "owner_profile.last_name", "text", "≤ 60"),
        E("ชื่อเล่น", "owner_profile.nickname", "text", "≤ 30"), E("เบอร์โทร", "owner_profile.phone_e164", "tel input แสดงแบบ 081-234-5678", "R-22; เบอร์ซ้ำ → แถบเตือน + ลิงก์ลูกค้าเดิม"),
        E("อีเมล", "owner_profile.email", "email", ""), E("วันเกิด", "owner_profile.birth_date", "date (พ.ศ.)", "")]),
     ("ที่อยู่", [E("ที่อยู่", "owner_profile.address_line", "text", ""), E("ตำบล/แขวง", "owner_profile.subdistrict", "autocomplete จากรหัสไปรษณีย์", ""),
                  E("อำเภอ/เขต", "owner_profile.district", "autocomplete", ""), E("จังหวัด", "owner_profile.province", "select 77 จังหวัด", ""),
                  E("รหัสไปรษณีย์", "owner_profile.postal_code", "text 5 หลัก", "^\\d{5}$")]),
     ("ข้อมูลของร้าน", [E("รู้จักร้านจาก", "customer.source_channel", "select", ""), E("รายละเอียด", "customer.referral_note", "text", ""),
        E("ผู้ติดต่อฉุกเฉิน", "customer.emergency_contact_name", "text", ""), E("เบอร์ฉุกเฉิน", "customer.emergency_contact_phone", "tel", "R-22"),
        E("ยินยอมใช้รูปน้อง", "customer.photo_consent", "radio ยินยอม/ไม่ยินยอม/ยังไม่ถาม", ""),
        E("ยกเว้นมัดจำ", "customer.deposit_exempt", "toggle", "owner เท่านั้น"), E("โน้ตภายใน", "customer.internal_note", "textarea", "≤ 2000")])],
    [("บันทึก", "customers.create / customers.update", "", "→ C-09")])
scr("C-11", "console", "/console/pets/[petId]?tab=profile|grooming|health|vaccines|photos|weight", "น้อง", "OFS",
    "US-03-02, US-03-03, US-03-04, US-03-05, US-03-06, US-03-07, US-03-11", "โปรไฟล์น้องครบทุกมิติ", ["pets.get", "photos.list"],
    [("แท็บโปรไฟล์ (ข้อมูลกลางของน้อง)", [E("รูปโปรไฟล์", "pet.profile_file_id", "image upload crop 1:1", "R-25"), E("ชื่อ", "pet.name", "text", "บังคับ 1–40"),
        E("ชนิด", "pet.species", "segmented หมา/แมว/อื่นๆ", "บังคับ"), E("ระบุชนิด", "pet.species_other", "text", "บังคับเมื่อ อื่นๆ"),
        E("พันธุ์", "pet.breed", "combobox รายการพันธุ์ + พิมพ์เอง", ""), E("เพศ", "pet.sex", "segmented", ""), E("วันเกิด", "pet.birth_date", "date", "≤ วันนี้"),
        E("อายุโดยประมาณ (เดือน)", "pet.age_estimate_months", "number", "แสดงเมื่อไม่มีวันเกิด"), E("ทำหมัน", "pet.neutered", "ใช่/ไม่/ไม่ทราบ", ""),
        E("สี", "pet.color", "text", ""), E("ไมโครชิป", "pet.microchip_no", "text", "15 หลัก"),
        E("ประเภทขน", "pet.coat_type", "select + รูปตัวอย่าง", "บังคับ (ใช้คิดราคา R-02)"), R("สถานะ", "pet.status", "enum badge"),
        R("อายุ", "calc: R-12 ageInMonths", "'2 ปี 6 เดือน'")]),
     ("แท็บกรูม", [E("ทรงที่ชอบ", "pet_shop_profile.preferred_style", "text", ""), E("เบอร์ใบมีด", "pet_shop_profile.blade_no", "text", ""),
        E("แชมพูที่ใช้ได้", "pet_shop_profile.shampoo_ok", "text", ""), E("แชมพูที่ห้ามใช้", "pet_shop_profile.shampoo_avoid", "text (แดง)", ""),
        E("รูปทรงโปรด", "pet_shop_profile.favorite_style_photo_id", "เลือกจากคลังรูป", ""), E("รอบกรูม (วัน)", "pet_shop_profile.groom_interval_days", "number", "7–180, ว่าง = อัตโนมัติ R-17"),
        R("กรูมล่าสุด", "pet_shop_profile.last_groomed_at", "date"), R("ครบรอบถัดไป", "calc: R-17", "date + ที่มา")]),
     ("แท็บสุขภาพ & นิสัย", [E("แพ้", "pet_shop_profile.allergies", "textarea", ""), E("โรคประจำตัว", "pet_shop_profile.conditions", "textarea", ""),
        E("ยาที่ทานประจำ", "pet_shop_profile.medications", "textarea", ""), E("คลินิกประจำ", "pet_shop_profile.vet_clinic_name", "text", ""),
        E("เบอร์คลินิก", "pet_shop_profile.vet_clinic_phone", "tel", "R-22"), E("ป้ายนิสัย", "pet_temperament_flag.flag", "multi-select chips + โน้ตต่อป้าย", ""),
        E("โน้ตภายใน", "pet_shop_profile.internal_note", "textarea เหลือง 'ลูกค้าไม่เห็น'", ""), E("โน้ตถึงลูกค้า", "pet_shop_profile.shared_note", "textarea ฟ้า 'ลูกค้าเห็นใน LINE'", "")]),
     ("แท็บวัคซีน", [R("รายการ", "pet_vaccination.vaccine_code", "ตาราง: ชื่อวัคซีน, วันที่ฉีด, หมดอายุ (แดงถ้าหมด/ใกล้หมด 30 วัน), สถานะ, ที่มา, รูปหลักฐาน"),
        W("เพิ่ม: วัคซีน", "pet_vaccination.vaccine_code", "select ตาม species", ""), W("วันที่ฉีด", "pet_vaccination.administered_on", "date", ""),
        W("หมดอายุ", "pet_vaccination.expires_on", "date (prefill + default_validity_months)", ""), W("รูปสมุดวัคซีน", "pet_vaccination.proof_file_id", "upload", "")]),
     ("แท็บรูป", [R("คลังรูป", "pet_photo.file_id", "grid + filter ก่อน/หลัง/ระหว่างพัก + วันที่ (taken_at)"), R("คำบรรยาย", "pet_photo.caption")]),
     ("แท็บน้ำหนัก", [R("กราฟ", "pet_weight.weight_grams", "line chart ตาม measured_at"), W("เพิ่มน้ำหนัก", "pet_weight.weight_grams", "number กก.", "0.1–150")])],
    [("บันทึก (แต่ละแท็บ)", "pets.update / pets.updateShopProfile / pets.setFlags", "OF (staff แก้แท็บกรูม/สุขภาพได้)", "toast"),
     ("เพิ่มวัคซีน", "vaccinations.create", "OF", ""), ("ยืนยัน/ปฏิเสธวัคซีน", "vaccinations.verify / vaccinations.reject", "status pending_review", ""),
     ("เพิ่มรูป", "staff.uploadUrl → photos.add", "", ""), ("บันทึกน้ำหนัก", "pets.addWeight", "", ""),
     ("น้องจากไป / ย้ายบ้าน", "pets.setStatus", "OF", "dialog ยืนยัน + ข้อความเห็นใจ; หยุดแจ้งเตือนทั้งหมด")])
scr("C-12", "console", "/console/link-requests", "คำขอจับคู่บัญชี LINE", "OF", "US-11-01", "ยืนยันว่าลูกค้าที่สมัครใน LINE คือลูกค้าเดิม (กันคนอื่นใช้เบอร์)", ["linkRequests.list"],
    [("คำขอ", [R("LINE", "line_identity.display_name", "รูป + ชื่อ"), R("เบอร์ที่กรอก", "customer_link_request.phone_entered", "phone"),
               R("ลูกค้าเดิมที่ตรง", "owner_profile.first_name", "ชื่อ + น้อง + มาล่าสุด"), R("ขอเมื่อ", "customer_link_request.created_at", "date time")])],
    [("ใช่ คนเดียวกัน", "linkRequests.approve", "", ""), ("ไม่ใช่", "linkRequests.reject", "", "")], ["คำแนะนำบนหน้า: ทักแชทถามชื่อน้องหรือวันที่มาครั้งล่าสุดก่อนยืนยัน"])
scr("C-13", "console", "/console/hotel?date=", "Room map", "OFS", "US-06-04", "ผังห้องรายวัน ลากย้ายห้อง ตั้งสถานะทำความสะอาด", ["roomMap.get"],
    [("ตัวกรอง", [Q("วันที่", "calc: date", "date picker", ""), Q("โซน", "room_unit.zone", "select", "")]),
     ("การ์ดห้อง (grid ตาม zone/sort_order)", [R("รหัสห้อง", "room_unit.code", "ตัวใหญ่"), R("ประเภท", "room_type.name_th", "เล็ก"),
        R("สถานะห้อง", "room_unit.status", "เทาถ้า maintenance"), R("ทำความสะอาด", "room_unit.housekeeping", "ไอคอน 🧹 ถ้า dirty"),
        R("น้องที่พัก", "pet.name", "ชื่อ + รูป + ป้ายนิสัย"), R("เช็คเอาท์", "stay.check_out_date", "date + 'ออกวันนี้' ส้ม"),
        R("เข้าวันนี้", "calc: RoomMap.units.arrivingToday", "ป้ายเขียว"), R("จองถัดไป", "calc: RoomMap.units.nextArrivalDate", "date เล็ก")])],
    [("ลากน้องไปห้องอื่น", "stays.changeRoom", "OF", "ROOM_TAKEN → เด้งกลับ"), ("สลับ สะอาด/ต้องทำความสะอาด", "roomUnits.housekeeping", "", ""),
     ("คลิกน้อง", "—", "", "→ C-15")])
scr("C-14", "console", "/console/hotel/today?date=", "เข้า-ออกวันนี้", "OFS", "US-06-12", "รายชื่อเช็คอิน/เช็คเอาท์/พักอยู่", ["stays.today"],
    [("3 คอลัมน์", [R("เข้า", "stay.check_in_date", "การ์ด: เวลาที่จะมา (expected_check_in_time), น้อง, ห้อง, ฟอร์มรับฝาก ✓/✗, ข้อตกลง ✓/✗, วัคซีน (R-11) ✓/⚠"),
        R("ออก", "stay.check_out_date", "การ์ด: เวลารับ, น้อง, ห้อง, add-on, อาบน้ำก่อนกลับ (bundle) สถานะ"),
        R("พักอยู่", "stay.status", "การ์ด: น้อง, ห้อง, คืนที่ x/y, งานค้าง")])],
    [("เช็คอิน", "—", "status reserved", "→ C-15 ขั้นรับฝาก"), ("เช็คเอาท์", "—", "checked_in", "→ C-15 ขั้นเช็คเอาท์")])
scr("C-15", "console", "/console/stays/[stayId]?step=intake|checkin|stay|checkout", "การพัก", "OF",
    "US-06-05, US-06-06, US-06-08, US-06-09, US-06-11", "ทำทุกขั้นของการรับฝากในหน้าเดียว", ["stays.get"],
    [("หัว", [R("น้อง", "pet.name", "รูป + ชื่อ + ป้ายนิสัย + แพ้"), R("ห้อง", "room_unit.code", "+ ประเภท"), R("วันที่", "stay.check_in_date", "date → date (nights คืน)"),
              R("สถานะ", "stay.status", "enum badge"), R("วัคซีน", "calc: R-11", "✓ / รายการที่ขาด-หมดอายุ (แดง)")]),
     ("ฟอร์มรับฝาก", [E("ยี่ห้ออาหาร", "stay_intake.food_brand", "text", ""), E("ปริมาณ", "stay_intake.food_amount", "text", "เช่น 1 ถ้วย"),
        E("เวลาให้อาหาร", "stay_intake.feeding_times", "chips เวลา + เพิ่ม", "0–6"), E("เจ้าของเตรียมอาหารมา", "stay_intake.food_provided_by_owner", "toggle", ""),
        E("พาเดินต่อวัน", "stay_intake.walks_per_day", "stepper 0–6", ""), E("สภาพร่างกายตอนรับ", "stay_intake.condition_note", "textarea", ""),
        E("รูปสภาพตอนรับ", "stay_intake.condition_photo_ids", "upload ≤ 6", ""), E("ผู้ติดต่อฉุกเฉิน", "stay_intake.emergency_contact_name", "text", "บังคับ"),
        E("เบอร์ฉุกเฉิน", "stay_intake.emergency_contact_phone", "tel", "บังคับ R-22"), E("คลินิก", "stay_intake.vet_clinic_name", "text", ""),
        E("เบอร์คลินิก", "stay_intake.vet_clinic_phone", "tel", ""),
        E("ยา: ชื่อ", "stay_medication.name", "แถวซ้ำได้", ""), E("ยา: ขนาด", "stay_medication.dose", "text", ""), E("ยา: เวลา", "stay_medication.times", "chips เวลา", "≥ 1"),
        E("ยา: วิธีให้", "stay_medication.instructions", "text", ""),
        E("ของที่นำมา", "stay_belonging.item", "แถวซ้ำได้: ชื่อ + จำนวน (quantity) + รูป (photo_file_id)", "")]),
     ("ข้อตกลงรับฝาก", [R("ข้อความ", "branch_policy.boarding_agreement_text", "กล่องเลื่อนอ่าน"),
        W("วงเงินพาไปหาหมอฉุกเฉิน", "consent_document.emergency_vet_limit_satang", "money input", "≥ 0"),
        W("ชื่อผู้เซ็น", "consent_document.signer_name", "text", "บังคับ"), W("ลายเซ็น", "consent_document.signature_file_id", "signature pad", "บังคับ")]),
     ("เช็คอิน", [W("น้ำหนักวันเข้า", "stay.weight_grams_in", "number กก.", ""),
        W("เหตุผลข้ามการตรวจวัคซีน", "stay.vaccine_override_reason", "textarea (แสดงเมื่อ R-11 ไม่ผ่าน)", "≥ 3 — บันทึก audit")]),
     ("ระหว่างพัก", [R("งานวันนี้", "care_task.title", "checklist + เวลา + ผู้ทำ"), R("Add-on", "stay_addon.name_snapshot", "list + จำนวน + money"),
        R("อัปเดตที่ส่งลูกค้า", "pet_photo.file_id", "grid รูป stay"), E("วันเช็คเอาท์", "stay.check_out_date", "date", "ขยาย/ลด (R-28)")]),
     ("เช็คเอาท์", [W("น้ำหนักวันออก", "stay.weight_grams_out", "number กก.", ""), W("ของคืนครบ", "stay_belonging.returned_at", "checklist ของที่นำมา", "ติ๊กครบ หรือใส่หมายเหตุ"),
        R("สรุปค่าใช้จ่าย", "calc: room_total + addons + bundle", "money → ปุ่มไปบิล")])],
    [("บันทึกฟอร์ม", "stays.saveIntake", "", ""), ("เซ็นข้อตกลง", "stays.signAgreement", "", ""), ("เช็คอิน", "stays.checkIn", "reserved + ฟอร์มครบ + เซ็นแล้ว", ""),
     ("เพิ่ม add-on", "stays.addAddon", "", ""), ("เปลี่ยนวัน", "stays.changeDates", "", ""), ("ส่งอัปเดตรูป", "stays.postUpdate", "checked_in", ""),
     ("เช็คเอาท์", "stays.checkOut", "checked_in", "→ C-18 บิล"), ("ไม่มา", "stays.noShow", "reserved", ""),
     ("ลบ add-on", "stays.removeAddon", "บิลยังไม่ปิด", "ยืนยันก่อนลบ"), ("ยกเลิกการพัก", "stays.cancel", "reserved", "dialog เหตุผล + ผลเงิน R-07")])
scr("C-16", "console", "/console/hotel/tasks?date=", "งานดูแลรายวัน (มุมมองร้าน)", "OFS", "US-06-09", "ตารางงานดูแลทุกตัว", ["careTasks.list"],
    [("ตาราง (จัดกลุ่มตามเวลา)", [R("เวลา", "care_task.due_at", "time"), R("งาน", "care_task.title", "ไอคอนตาม task_type"), R("น้อง/ห้อง", "pet.name", "+ room_unit.code"),
        R("สถานะ", "care_task.status", "checkbox; แดงถ้าเลยกำหนด 30 นาที"), R("ทำโดย/เมื่อ", "care_task.done_by", "ชื่อ + time (done_at)"), R("โน้ต", "care_task.note", "")])],
    [("ทำแล้ว", "careTasks.done", "pending", ""), ("ข้าม", "careTasks.skip", "pending", "เหตุผลบังคับ")])
scr("C-17", "console", "/console/daycare?date=", "Daycare วันนี้", "OFS", "US-06-13", "เช็คอิน/เอาท์ Daycare", ["daycare.list"],
    [("รายการ", [R("น้อง", "pet.name", "รูป + ป้าย"), R("รอบ", "daycare_session_type.name_th", ""), R("สถานะ", "daycare_visit.status", "enum"),
                 R("เข้า/ออก", "daycare_visit.checked_in_at", "time / time (checked_out_at)"), R("วัคซีน", "calc: R-11", "✓/⚠")])],
    [("เช็คอิน", "daycare.check_in", "reserved", ""), ("เช็คเอาท์", "daycare.check_out", "checked_in", ""), ("ไม่มา", "daycare.no_show", "reserved", ""),
     ("ยกเลิก", "daycare.cancel", "reserved", "dialog เหตุผล")])
scr("C-18", "console", "/console/bills/[billId]", "บิล (คิดเงิน)", "OF", "US-08-01, US-08-02, US-08-03, US-08-04, US-10-05, US-07-01",
    "รวมทุกรายการ หักมัดจำ/เครดิต/แพ็กเกจ รับชำระ ปิดบิล", ["bills.get"],
    [("ลูกค้า", [R("ชื่อ", "owner_profile.first_name", "ลิงก์ C-09"), R("เครดิตคงเหลือ", "customer.credit_balance_satang", "money"),
                 R("แพ็กเกจที่ใช้ได้", "customer_package.sessions_used", "chips 'อาบน้ำ เหลือ 3'")]),
     ("รายการ", [R("รายการ", "bill_line.description", "ชื่อ + ชื่อน้อง (pet_id)"), R("ประเภท", "bill_line.line_type", "ไอคอน"), R("จำนวน", "bill_line.quantity", "number"),
                 R("ราคา/หน่วย", "bill_line.unit_price_satang", "money always"), E("ส่วนลด", "bill_line.line_discount_satang", "money input + เหตุผล", "R-15"),
                 R("รวม", "bill_line.line_total_satang", "money always"), E("ช่าง", "bill_line.performer_id", "select (บรรทัดบริการ)", "")]),
     ("เพิ่มรายการ", [W("สินค้า/บริการด่วน", "bill_line.description", "text + ราคา (unit_price_satang) + จำนวน", ""),
                      W("ขายแพ็กเกจ", "bill_line.ref_id", "select package_template + น้อง", ""), W("ใช้สิทธิ์แพ็กเกจ", "bill_line.ref_id", "select customer_package ที่ R-14 ok", "")]),
     ("สรุป", [R("รวม", "bill.subtotal_satang", "money always"), E("ส่วนลดท้ายบิล", "bill.bill_discount_satang", "money + เหตุผล (bill_discount_reason)", "R-15 front_desk ≤ 20%"),
               R("ยอดสุทธิ", "bill.total_satang", "money always ตัวใหญ่"), R("ชำระแล้ว", "bill.paid_satang", "money"), R("ค้างชำระ", "calc: total − paid", "money แดง"),
               R("เงินทอน", "bill.change_satang", "money เขียว")]),
     ("การชำระ", [R("รายการรับเงิน", "payment.method", "แถว: วิธี (enum), money, เลขอ้างอิง, เวลา, สถานะ"),
        W("วิธีรับเงิน", "payment.method", "ปุ่มใหญ่: เงินสด / PromptPay QR / โอน / บัตร / เครดิต", ""),
        W("รับเงินสด", "payment.tendered_satang", "money keypad + ปุ่มลัด ฿100 ฿500 ฿1000 พอดี", "R-15"), W("ยอด (วิธีอื่น)", "payment.amount_satang", "money (prefill = ค้าง)", "≤ ค้าง"),
        W("เลขอ้างอิง", "payment.reference", "text", "บัตร: บังคับ"), R("QR PromptPay", "calc: R-30", "QR + ยอด + ชื่อบัญชี (เมื่อเลือก PromptPay)")])],
    [("เพิ่มรายการ", "bills.addLine", "status open", "สินค้า/บริการด่วน, ขายแพ็กเกจ, ใช้สิทธิ์แพ็กเกจ (R-14)"),
     ("แก้บรรทัด (ส่วนลด/ช่าง/จำนวน)", "bills.updateLine", "status open", "ส่วนลดเกินสิทธิ์ role → DISCOUNT_LIMIT_EXCEEDED (R-15)"),
     ("ลบบรรทัด", "bills.removeLine", "status open, เฉพาะ quick_item/package", "บรรทัดจากบริการลบไม่ได้ (ต้องแก้ที่นัด)"),
     ("ส่วนลดท้ายบิล", "bills.setDiscount", "status open", "เหตุผลบังคับ"),
     ("แสดง QR PromptPay", "bills.promptpayQr", "status open, ค้าง > 0, เลือกวิธี PromptPay", "QR ยอดค้าง (R-30) — ลูกค้าโอนแล้วกด 'รับเงิน' วิธี promptpay"),
     ("รับเงิน", "bills.addPayment", "status open, ค้าง > 0", "อัปเดตยอด; STALE_BILL → รีโหลด"), ("ยกเลิกรายการรับเงิน", "bills.voidPayment", "open", "เหตุผล"),
     ("ปิดบิล", "bills.close", "ค้าง = 0", "→ C-20 ใบเสร็จ + ส่ง LINE อัตโนมัติ"), ("Void บิล", "bills.void", "owner, paid", "dialog เหตุผล + สรุปผลกระทบ")],
    ["หน้าจอใช้ได้บนแท็บเล็ต (ปุ่ม ≥ 44px)", "ห้ามคำนวณยอดเองฝั่ง client — แสดงค่าจาก server (ป้องกันยอดไม่ตรง)"])
scr("C-19", "console", "/console/bills?status=&date=", "รายการบิล", "OF", "US-08-01, US-08-06", "ดูบิลวันนี้/ค้นบิล", ["bills.list"],
    [("ตาราง", [R("เลขใบเสร็จ", "bill.receipt_no", "mono ('—' ถ้ายัง open)"), R("ลูกค้า", "owner_profile.first_name"), R("ยอด", "bill.total_satang", "money"),
                R("ชำระแล้ว", "bill.paid_satang", "money"), R("วิธีจ่าย", "payment.method", "ไอคอน"), R("สถานะ", "bill.status", "enum badge"),
                R("เวลา", "bill.closed_at", "time (หรือ opened_at)")])],
    [("+ บิลขายของ", "bills.open", "", "→ C-18 (customerId ว่างได้)")])
scr("C-20", "console", "/console/bills/[billId]/receipt", "ใบเสร็จ (พิมพ์)", "OF", "US-08-05", "ใบเสร็จรับเงินขนาด 58/80 มม. หรือ A5", ["bills.receipt"],
    [("ใบเสร็จ", [R("โลโก้/ชื่อร้าน/ที่อยู่/โทร", "branch.name", "หัวกระดาษ"), R("เลขที่", "bill.receipt_no", ""), R("วันที่", "bill.closed_at", "date + time"),
        R("ลูกค้า", "calc: ชื่อ-นามสกุล", ""), R("รายการ", "bill_line.description", "qty × ราคา = รวม (money always)"), R("ส่วนลด", "bill.bill_discount_satang", "money"),
        R("ยอดสุทธิ", "bill.total_satang", "money always ตัวหนา"), R("ชำระโดย", "payment.method", "วิธี + money"), R("เงินทอน", "bill.change_satang", "money"),
        R("แพ็กเกจคงเหลือ", "customer_package.sessions_used", "'อาบน้ำ เหลือ 3 ครั้ง หมดอายุ …'"), R("ผู้รับเงิน", "staff_user.display_name", ""),
        R("VOID", "bill.status", "ลายน้ำ 'ยกเลิก' เมื่อ void")])],
    [("พิมพ์", "—", "", "window.print() + CSS @page 58mm/80mm/A5 ตาม SP-05"), ("ส่ง LINE อีกครั้ง", "bills.sendReceipt", "ลูกค้ามี LINE", "")],
    ["หัวเอกสาร 'ใบเสร็จรับเงิน' (ไม่ใช่ใบกำกับภาษี)"])
scr("C-21", "console", "/console/report-cards", "Report card รอตรวจ", "OF", "US-10-01", "ตรวจก่อนส่งลูกค้า (เมื่อเปิด report_card_requires_review)", ["reportCards.list"],
    [("การ์ด", [R("น้อง", "pet.name", "รูป after"), R("ช่าง", "staff_user.display_name"), R("ผลตรวจ", "report_card.skin", "ป้าย ผิว/หู/เล็บ/ฟัน/ปรสิต (enum)"),
                E("ข้อความถึงลูกค้า", "report_card.staff_note", "textarea", "≤ 500"), E("คำแนะนำ", "report_card.recommendation", "textarea", "")])],
    [("บันทึก", "reportCards.update", "", ""), ("ส่งลูกค้า", "reportCards.approve", "pending_review", "")])
scr("C-22", "console", "/console/messages", "ข้อความที่ไม่ได้ส่ง", "OF", "US-13-06", "ข้อความที่ระบบข้าม (โควตาหมด/ไม่ใช่เพื่อน/โหมดประหยัด) ให้ร้านส่งเองในแชท",
    ["line.skipped", "line.status"],
    [("โควตา", [R("ใช้ไป/โควตา", "calc: LineStatus.usedThisMonth", "progress bar (ส้ม ≥ 70%, แดง ≥ 90%)"), R("โหมดประหยัด", "branch_policy.economy_mode", "สถานะ + ลิงก์ไปตั้งค่า")]),
     ("รายการ", [R("ถึง", "calc: ชื่อลูกค้า", ""), R("เรื่อง", "notification.template_key", "ป้ายภาษาไทยของ template"), R("เหตุผล", "notification.skip_reason", "enum"),
                 R("ข้อความ", "calc: render template", "กล่องข้อความ + ปุ่มคัดลอก"), R("เวลา", "notification.created_at", "time ago")])],
    [("คัดลอกข้อความ", "—", "", "copy to clipboard แล้วเปิดแชท LINE OA Manager")])
scr("C-23", "console", "/console/reports/sales", "รายงานยอดขาย", "O", "US-12-02, US-12-06", "ยอดขายตามวัน/บริการ/ช่าง/วิธีจ่าย", ["reports.sales"],
    [("ตัวกรอง", [Q("ช่วงวันที่", "calc: from/to", "date range + ปุ่มลัด วันนี้/7 วัน/เดือนนี้/เดือนก่อน", "≤ 366 วัน"), Q("จัดกลุ่ม", "calc: groupBy", "segmented", "")]),
     ("ผล", [R("ยอดรวม/ส่วนลด/สุทธิ", "calc: SalesReport.totals", "การ์ด money"), R("กราฟ", "calc: SalesReport.rows", "bar chart ตามวัน"),
             R("ตาราง", "calc: SalesReport.rows", "key, จำนวนบิล, gross, discount, net (money)"), R("แยกวิธีจ่าย", "payment.method", "ตาราง money")])],
    [("Export CSV", "exports.csv", "", "ดาวน์โหลด bills.csv / bill_lines.csv")])
scr("C-24", "console", "/console/reports/commissions", "รายงานค่ามือ", "O", "US-12-03", "สรุปค่ามือต่อช่าง", ["reports.commissions"],
    [("ตัวกรอง", [Q("ช่วงวันที่", "calc: from/to", "date range", "")]),
     ("ตาราง", [R("ช่าง", "staff_user.display_name"), R("จำนวนงาน", "calc: count", "number"), R("ยอดฐาน", "commission_entry.base_satang", "money"),
                R("ค่ามือ", "commission_entry.amount_satang", "money ตัวหนา"), R("รายละเอียด", "commission_entry.bill_line_id", "expand: วันที่, ใบเสร็จ, บริการ, ฐาน, กติกา, ยอด")])],
    [("Export CSV", "exports.csv", "", "commissions.csv")])
scr("C-25", "console", "/console/reports/occupancy", "Occupancy", "O", "US-12-04", "อัตราเข้าพักรายวัน", ["reports.occupancy"],
    [("ผล", [Q("ช่วงวันที่", "calc: from/to", "date range", ""), R("กราฟ", "calc: OccupancyReport.days", "line chart %"),
             R("ตามประเภทห้อง", "calc: OccupancyReport.byRoomType", "ตาราง")])])
scr("C-26", "console", "/console/settings/audit", "Audit log", "O", "US-13-07", "ดูการกระทำสำคัญย้อนหลัง", ["audit.list"],
    [("ตัวกรอง", [Q("การกระทำ", "audit_log.action", "select ป้ายภาษาไทย", ""), Q("ช่วงวันที่", "calc: from/to", "date range", "")]),
     ("ตาราง", [R("เวลา", "audit_log.created_at", "date time"), R("ผู้ทำ", "audit_log.actor_id", "ชื่อ + 'ผ่านทีมช่วยเหลือ' ถ้า support"), R("การกระทำ", "audit_log.action", "ป้ายไทย"),
                R("รายการ", "audit_log.entity_type", "ลิงก์ไปเอกสาร"), R("เหตุผล", "audit_log.reason", ""), R("ก่อน/หลัง", "audit_log.before", "diff (after)")])])
# ---------------- settings
scr("C-30", "console", "/console/settings/shop", "ข้อมูลร้าน", "O", "US-02-01", "ข้อมูลที่ลูกค้าเห็น", ["branch.get"],
    [("ร้าน", [E("ชื่อร้าน", "branch.name", "text", "1–80"), E("โลโก้", "branch.logo_file_id", "upload crop 1:1", "R-25"), E("เบอร์โทร", "branch.phone", "tel", "R-22"),
               E("Facebook", "branch.facebook_url", "url", ""), E("Instagram", "branch.instagram_url", "url", ""), R("ลิงก์จอง", "branch.booking_slug", "copy URL /b/{slug}")]),
     ("ที่อยู่", [E("ที่อยู่", "branch.address_line", "text", ""), E("ตำบล/แขวง", "branch.subdistrict", "autocomplete", ""), E("อำเภอ/เขต", "branch.district", "autocomplete", ""),
                  E("จังหวัด", "branch.province", "select", ""), E("รหัสไปรษณีย์", "branch.postal_code", "text", "5 หลัก"),
                  E("ตำแหน่งบนแผนที่", "branch.latitude", "ปุ่ม 'ใช้ตำแหน่งปัจจุบัน' + ช่อง lat/lng (longitude)", "")]),
     ("ใบเสร็จ", [E("อักษรนำหน้าเลขใบเสร็จ", "branch.receipt_prefix", "text A-Z 1–3", ""), R("ตัวอย่าง", "calc: R-16", "'R69-00001'")])],
    [("บันทึก", "branch.update", "", "toast")])
scr("C-31", "console", "/console/settings/hours", "เวลาเปิด-ปิดและวันหยุด", "OF", "US-02-01, US-02-05", "ตั้งเวลาร้านและวันปิด", ["branch.get", "closures.list"],
    [("เวลาเปิดรายสัปดาห์ (owner)", [E("วัน", "branch_hours.weekday", "แถว จ.–อา.", ""), E("ปิดทั้งวัน", "branch_hours.is_closed", "toggle", ""),
        E("เปิด", "branch_hours.opens_at", "time select ทีละ 30 นาที", ""), E("ปิด", "branch_hours.closes_at", "time select", "> เปิด")]),
     ("วันปิด/ช่วงพิเศษ", [R("รายการ", "branch_closure.starts_at", "ตาราง: ช่วงเวลา, ขอบเขต (scope enum), เหตุผล, ที่มา (source)"),
        W("เริ่ม", "branch_closure.starts_at", "date + time", ""), W("สิ้นสุด", "branch_closure.ends_at", "date + time", "> เริ่ม"),
        W("ปิดเฉพาะ", "branch_closure.scope", "select ทั้งร้าน/กรูม/โรงแรม/Daycare", ""), W("เหตุผล", "branch_closure.reason", "text", "")])],
    [("บันทึกเวลา", "branch.setHours", "owner", "warnings → dialog รายการนัดที่ได้รับผล"), ("เพิ่มวันปิด", "closures.create", "", "affected → dialog"),
     ("ลบ", "closures.delete", "", ""), ("เพิ่มวันหยุดราชการ", "closures.importHolidays", "owner", "dialog เลือกวันจาก public_holiday")])
scr("C-32", "console", "/console/settings/modules", "บริการที่เปิด", "O", "US-02-02", "เปิด/ปิด กรูม · โรงแรม · Daycare", ["branch.get"],
    [("โมดูล", [E("กรูมมิ่ง", "branch.module_grooming", "toggle + คำอธิบาย", ""), E("โรงแรม", "branch.module_hotel", "toggle", ""), E("Daycare", "branch.module_daycare", "toggle", "")])],
    [("บันทึก", "branch.setModules", "", "warnings ใบจองค้าง")])
scr("C-33", "console", "/console/settings/policy", "นโยบายร้าน", "O", "US-02-04, US-07-03, US-07-04, US-05-05, US-06-05, US-07-06, US-10-04, US-13-06, US-12-05",
    "มัดจำ ยกเลิก การจอง วัคซีน ใบยินยอม การแจ้งเตือน", ["branch.get"],
    [("มัดจำ", [E("ประเภทมัดจำ", "branch_policy.default_deposit_type", "radio ไม่เก็บ/จำนวนคงที่/เปอร์เซ็นต์", ""),
                E("ค่ามัดจำ", "branch_policy.default_deposit_value", "money input (fixed) หรือ % (percent)", "fixed ≥ 0, percent 0–100"),
                R("ตัวอย่าง", "calc: R-06 กับยอด ฿850", "'ลูกค้าจ่ายมัดจำ ฿255'")]),
     ("ยกเลิก", [E("กรูม ยกเลิกฟรีก่อน (ชม.)", "branch_policy.grooming_free_cancel_hours", "number", "0–168"),
                 E("โรงแรม (ชม.)", "branch_policy.hotel_free_cancel_hours", "number", "0–336"), E("Daycare (ชม.)", "branch_policy.daycare_free_cancel_hours", "number", ""),
                 E("ยกเลิกกระชั้น ริบ (%)", "branch_policy.late_cancel_forfeit_percent", "slider 0–100 step 10", ""),
                 E("ส่วนที่ไม่ริบ คืนเป็น", "branch_policy.cancel_refund_mode", "radio เงินคืน/เครดิต/ให้ลูกค้าเลือก", ""),
                 E("ลูกค้าเลื่อน/ยกเลิกเองได้ถึง (ชม. ก่อนนัด)", "branch_policy.reschedule_cutoff_hours", "number", ""),
                 E("กด no-show ได้หลังเวลานัด (นาที)", "branch_policy.no_show_grace_minutes", "number", ""),
                 E("ข้อความนโยบายที่ลูกค้าเห็น", "branch_policy.policy_text", "textarea + ปุ่ม 'สร้างจากค่าข้างบน'", "≤ 2000")]),
     ("การจอง", [E("จองออนไลน์ล่วงหน้าอย่างน้อย (นาที)", "branch_policy.booking_lead_minutes", "select 0/30/60/120/240/1440", ""),
                 E("จองล่วงหน้าได้ไกลสุด (วัน)", "branch_policy.booking_horizon_days", "number", "1–180"), E("ช่วงเวลาเริ่มทุก", "branch_policy.slot_step_minutes", "select 5/10/15/30", ""),
                 E("เวลาเผื่อทำความสะอาดหลังแต่ละคิว", "branch_policy.buffer_minutes", "number", "0–60"),
                 E("รับคิวกรูมสูงสุดต่อวัน", "branch_policy.max_appointments_per_day", "number (ว่าง = ไม่จำกัด)", ""),
                 E("สูงสุดต่อช่างต่อวัน", "branch_policy.max_appointments_per_groomer_day", "number", ""),
                 E("เวลาให้ลูกค้าโอนมัดจำ (นาที)", "branch_policy.hold_minutes", "select 10/15/30/60", ""),
                 E("ยืนยันอัตโนมัติ: กรูม", "branch_policy.auto_confirm_grooming", "toggle", ""), E("ยืนยันอัตโนมัติ: โรงแรม", "branch_policy.auto_confirm_hotel", "toggle", ""),
                 E("ยืนยันอัตโนมัติ: Daycare", "branch_policy.auto_confirm_daycare", "toggle", ""),
                 E("เตือนร้านถ้ายังไม่อนุมัติภายใน (นาที)", "branch_policy.approval_timeout_minutes", "number", "")]),
     ("เงื่อนไขรับสัตว์", [E("วัคซีนที่ต้องมี (หมา)", "branch_policy.required_vaccines_dog", "multi-select vaccine_type", ""),
        E("วัคซีนที่ต้องมี (แมว)", "branch_policy.required_vaccines_cat", "multi-select", ""), E("ตรวจวัคซีนกับกรูมด้วย", "branch_policy.enforce_vaccines_grooming", "toggle", ""),
        E("สายพันธุ์ที่ไม่รับ", "branch_policy.rejected_breeds", "tag input", ""), E("น้ำหนักสูงสุดที่รับ (กก.)", "branch_policy.max_pet_weight_grams", "number กก.", "")]),
     ("เอกสาร", [E("ใบยินยอมก่อนกรูม", "branch_policy.grooming_consent_text", "textarea + ปุ่มใช้แม่แบบ", ""),
                 E("ข้อตกลงรับฝาก", "branch_policy.boarding_agreement_text", "textarea + แม่แบบ", "")]),
     ("หลังบริการ & ข้อความ", [E("เตือนลูกค้าก่อนนัด 24 ชม.", "branch_policy.reminder_24h_enabled", "toggle", ""),
        E("โหมดประหยัดข้อความ LINE", "branch_policy.economy_mode", "toggle + อธิบายว่าข้อความไหนจะไม่ส่ง (template economy = skip)", ""),
        E("รอบกรูมตั้งต้น (วัน)", "branch_policy.next_groom_default_days", "number", "7–180"), E("ลิงก์รีวิว Google", "branch_policy.google_review_url", "url", ""),
        E("ตรวจ Report card ก่อนส่ง", "branch_policy.report_card_requires_review", "toggle", ""),
        E("เวลาส่งสรุปรายวัน", "branch_policy.daily_summary_time", "time", "")])],
    [("บันทึก", "branch.updatePolicy", "", "toast 'มีผลกับการจองใหม่เท่านั้น'")])
scr("C-34", "console", "/console/settings/payment", "บัญชีรับเงิน PromptPay", "O", "US-02-03, US-07-01", "ตั้งบัญชีที่ลูกค้าโอนมัดจำ/ยอดค้าง", ["branch.get"],
    [("บัญชี", [E("ประเภท", "branch.promptpay_type", "radio เบอร์มือถือ/เลขบัตรประชาชน/เลขผู้เสียภาษี/e-Wallet", ""),
                E("หมายเลข PromptPay", "branch.promptpay_id", "text (แสดงแบบปิดบัง)", "R-30"), E("ชื่อบัญชี", "branch.promptpay_account_name", "text", "บังคับ"),
                W("รหัสผ่านของคุณ (ยืนยัน)", "calc: ไม่บันทึก", "password", "บังคับ"), R("QR ทดสอบ ฿1", "calc: R-30 amount 100", "QR ให้ทดลองสแกน")])],
    [("บันทึก", "branch.setPromptpay", "", "แจ้งเจ้าของร้านทุกคน")])
scr("C-35", "console", "/console/settings/line", "LINE OA และลิงก์จอง", "O", "US-02-06, US-02-07, US-13-06", "สถานะการเชื่อม + QR โปสเตอร์ + โควตา", ["line.status"],
    [("สถานะ", [R("การเชื่อม", "line_channel.status", "enum badge + 'ทีมงานตั้งค่าให้' ถ้ายัง pending"), R("LINE ID", "line_channel.bot_basic_id", "@xxx"),
                R("โควตา push/เดือน", "line_channel.monthly_push_quota", "number"), R("ใช้ไปเดือนนี้", "calc: LineStatus.usedThisMonth", "progress")]),
     ("ลิงก์และโปสเตอร์", [R("ลิงก์จองใน LINE", "calc: LineStatus.liffUrl", "copy"), R("ลิงก์หน้าร้าน", "branch.booking_slug", "copy /b/{slug}"),
        R("QR โปสเตอร์", "calc: QR ของ /b/{slug}", "พรีวิว A4/A5 + ปุ่มดาวน์โหลด PNG/PDF (สร้างฝั่ง client)")])])
scr("C-36", "console", "/console/settings/staff", "พนักงานและตารางงาน", "OF", "US-01-04, US-09-01", "เชิญพนักงาน กำหนดสิทธิ์ ตั้งเวลาทำงาน วันลา", ["staffUsers.list", "timeOff.list"],
    [("รายชื่อ", [R("ชื่อ", "staff_user.display_name", "รูป + ชื่อ"), R("บทบาท", "staff_user.role", "enum"), R("เป็นช่าง", "staff_user.is_groomer", "✓"),
                  R("สถานะ", "staff_user.status", "enum badge"), R("LINE", "calc: line linked", "ไอคอน"), R("เข้าล่าสุด", "staff_user.last_login_at", "time ago")]),
     ("เชิญ (owner)", [W("ชื่อเล่น", "staff_user.display_name", "text", "บังคับ"), W("อีเมล", "staff_user.email", "email", "ไม่บังคับ"),
                       W("บทบาท", "staff_user.role", "radio + คำอธิบายสิทธิ์", ""), W("เป็นช่างกรูม", "staff_user.is_groomer", "toggle", "")]),
     ("ตารางงานรายสัปดาห์", [E("วันทำงาน", "staff_working_hours.weekday", "แถว จ.–อา. toggle", ""), E("เริ่ม", "staff_working_hours.starts_at", "time", ""),
        E("เลิก", "staff_working_hours.ends_at", "time", "> เริ่ม"), E("พัก", "staff_working_hours.break_starts_at", "time–time (break_ends_at)", "อยู่ในช่วงทำงาน")]),
     ("วันลา", [R("รายการ", "staff_time_off.starts_at", "ช่วงเวลา + เหตุผล"), W("ช่วงลา", "staff_time_off.starts_at", "date-time range (ends_at)", ""),
                W("เหตุผล", "staff_time_off.reason", "text", "")])],
    [("เชิญ", "staffUsers.invite", "owner", "dialog แสดงลิงก์เชิญ + ปุ่มคัดลอก/ส่ง LINE"), ("แก้ไข/ปิดใช้งาน", "staffUsers.update", "owner", ""),
     ("ส่งคำเชิญใหม่", "staffUsers.resendInvite", "owner, invited", ""), ("บันทึกตารางงาน", "workingHours.set", "", "warnings"),
     ("เพิ่มวันลา", "timeOff.create", "", "affected"), ("ลบวันลา", "timeOff.delete", "", "")])
scr("C-37", "console", "/console/settings/services?scope=grooming|hotel|daycare", "บริการและราคา", "O", "US-04-01, US-04-02, US-04-03, US-04-04, US-04-05, US-06-06",
    "เมนูบริการ add-on ราคาตามขนาด/ขน เวลา ค่าบริการเพิ่ม", ["services.list", "sizeTiers.list", "surchargeTypes.list"],
    [("รายการบริการ", [R("ชื่อ", "service.name_th", "+ ป้าย add-on"), R("หมวด", "service.category", "enum"), R("ราคาเริ่ม", "calc: min price", "money"),
                       R("จองออนไลน์", "service.online_bookable", "toggle inline"), R("สถานะ", "service.status", "enum")]),
     ("ฟอร์มบริการ", [E("ชื่อบริการ", "service.name_th", "text", "บังคับ"), E("หมวด", "service.category", "select", ""), E("คำอธิบาย", "service.description", "textarea", ""),
        E("รูป", "service.photo_file_id", "upload", ""), E("ชนิดสัตว์ที่รับ", "service.species_allowed", "multi-check (ว่าง = ทุกชนิด)", ""),
        E("เป็น add-on", "service.is_addon", "toggle", ""), E("คิดต่อวัน (โรงแรม)", "service.addon_per_day", "toggle", "scope hotel"),
        E("ใช้กับบริการหลัก", "service_addon_link.base_service_id", "multi-select", "add-on เท่านั้น"), E("ต้นทุนโดยประมาณ", "service.est_cost_satang", "money", ""),
        E("ลำดับ", "service.sort_order", "drag handle", "")]),
     ("ตารางราคา (แถว = ขนาด, คอลัมน์ = ขนสั้น/ขนยาว หรือ 'ทุกแบบ')", [E("ราคา", "service_price.price_satang", "money cell", "≥ 0; ช่องว่าง = ไม่เปิดให้ขนาดนี้"),
        E("เวลา (นาที)", "service_price.duration_minutes", "number cell", "0–600"), E("แยกตามขน", "service_price.coat_group", "toggle ทั้งตาราง", "")]),
     ("ค่าบริการเพิ่มหน้างาน", [E("ชื่อ", "surcharge_type.name_th", "text", ""), E("ราคาตั้งต้น", "surcharge_type.default_amount_satang", "money", ""),
                               E("ใช้งาน", "surcharge_type.status", "toggle", "")])],
    [("บันทึกบริการ", "services.create / services.update", "", ""), ("บันทึกราคา", "services.setPrices", "", ""), ("บันทึก add-on link", "services.setAddonLinks", "", ""),
     ("บันทึกค่าบริการเพิ่ม", "surchargeTypes.upsert", "", "")])
scr("C-38", "console", "/console/settings/size-tiers", "ขนาดตามน้ำหนัก", "O", "US-04-02", "กำหนดช่วงน้ำหนัก S/M/L", ["sizeTiers.list"],
    [("แท็บหมา/แมว", [E("รหัส", "size_tier.code", "text", "A-Z 1–4"), E("ชื่อที่แสดง", "size_tier.label_th", "text", ""),
        E("ตั้งแต่ (กก.)", "size_tier.min_weight_grams", "number กก.", "แถวแรก 0; = ขอบบนแถวก่อน"), E("ไม่ถึง (กก.)", "size_tier.max_weight_grams", "number กก. (แถวสุดท้ายว่าง)", "> ตั้งแต่")])],
    [("บันทึก", "sizeTiers.set", "", "SIZE_TIER_OVERLAP ไฮไลต์แถว")])
scr("C-39", "console", "/console/settings/rooms", "ห้องพัก", "O", "US-06-01, US-06-02", "ประเภทห้อง เงื่อนไข ราคา และห้องรายยูนิต", ["roomTypes.list", "roomUnits.list", "sizeTiers.list"],
    [("ประเภทห้อง", [E("ชื่อ", "room_type.name_th", "text", "บังคับ"), E("คำอธิบาย", "room_type.description", "textarea", ""), E("รูป", "room_type.photo_file_id", "upload", ""),
        E("ชนิดสัตว์", "room_type.species_allowed", "multi-check", ""), E("น้ำหนักสูงสุด (กก.)", "room_type.max_weight_grams", "number", ""),
        E("อายุขั้นต่ำ (เดือน)", "room_type.min_age_months", "number", ""), E("รับติดสัด", "room_type.allow_in_heat", "toggle", ""),
        E("รับน้องดุ/ไม่ถูกกับตัวอื่น", "room_type.allow_reactive", "toggle", ""), E("สิ่งอำนวยความสะดวก", "room_type.amenities", "chips", ""),
        E("รวมในราคา", "room_type.included_text", "textarea", ""), E("จองออนไลน์", "room_type.online_bookable", "toggle", ""), E("ใช้งาน", "room_type.status", "toggle", "")]),
     ("ราคาต่อคืน", [E("ทุกขนาด / ตามขนาด", "room_rate.size_tier_id", "toggle แยกตามขนาด", ""), E("ราคา/คืน", "room_rate.nightly_price_satang", "money ต่อแถว", "≥ 0")]),
     ("ห้อง", [E("รหัสห้อง", "room_unit.code", "text", "ไม่ซ้ำ"), E("ประเภท", "room_unit.room_type_id", "select", ""), E("โซน", "room_unit.zone", "text", ""),
               E("สถานะ", "room_unit.status", "select ใช้งาน/ซ่อม/เลิกใช้", ""), E("ลำดับ", "room_unit.sort_order", "drag", "")])],
    [("บันทึกประเภท", "roomTypes.create / roomTypes.update", "", ""), ("บันทึกราคา", "roomTypes.setRates", "", ""), ("บันทึกห้อง", "roomUnits.upsert", "", "IN_USE/CODE_TAKEN")])
scr("C-40", "console", "/console/settings/daycare", "Daycare", "O", "US-06-13", "รอบ ความจุ ราคา", ["daycareTypes.list", "sizeTiers.list"],
    [("รอบ", [E("รอบ", "daycare_session_type.session", "fixed: เต็มวัน/เช้า/บ่าย", ""), E("ชื่อ", "daycare_session_type.name_th", "text", ""),
              E("เวลา", "daycare_session_type.starts_at", "time–time (ends_at)", ""), E("รับได้ (ตัว)", "daycare_session_type.capacity", "number", "1–200"),
              E("ใช้งาน", "daycare_session_type.status", "toggle", ""), E("ราคา", "daycare_rate.price_satang", "money ต่อขนาด (size_tier_id)", "")])],
    [("บันทึก", "daycareTypes.upsert", "", "")])
scr("C-41", "console", "/console/settings/packages", "แพ็กเกจ", "O", "US-10-05", "แพ็กเกจหลายครั้งที่ขาย", ["packageTemplates.list", "services.list"],
    [("แพ็กเกจ", [E("ชื่อ", "package_template.name_th", "text", ""), E("บริการ", "package_template.service_id", "select", ""), E("ขนาด", "package_template.size_tier_id", "select (ทุกขนาด)", ""),
                  E("จำนวนครั้ง", "package_template.sessions_count", "number", "2–50"), E("ราคา", "package_template.price_satang", "money", "> 0"),
                  R("ตกครั้งละ", "calc: R-14 unitValue", "money"), E("อายุ (วัน)", "package_template.validity_days", "number", "1–730"),
                  E("ใช้ร่วมกัน", "package_template.share_scope", "radio น้องตัวเดียว/ทุกตัวในบ้าน", ""), E("ขายอยู่", "package_template.status", "toggle", "")])],
    [("บันทึก", "packageTemplates.upsert", "", "")])
scr("C-42", "console", "/console/settings/commissions", "ค่ามือ", "O", "US-09-02", "กติกาค่ามือ (เจาะจงชนะกว้าง)", ["commissionRules.list", "services.list", "staffUsers.list"],
    [("กติกา", [E("บริการ", "commission_rule.service_id", "select (ทุกบริการ)", ""), E("ช่าง", "commission_rule.staff_user_id", "select (ทุกคน)", ""),
                E("แบบ", "commission_rule.type", "segmented % / บาท", ""), E("ค่า", "commission_rule.value", "% (2 ตำแหน่ง → bps) หรือ money", ""),
                R("ลำดับที่ใช้", "calc: R-13 precedence", "คำอธิบายใต้ตาราง")])],
    [("บันทึก", "commissionRules.set", "", "")])
scr("C-43", "console", "/console/settings/stations", "โต๊ะกรูม", "O", "US-05-01", "จำนวนโต๊ะ = คิวพร้อมกันสูงสุด", ["stations.list"],
    [("โต๊ะ", [E("ชื่อ", "groom_station.name", "text", ""), E("ลำดับ", "groom_station.sort_order", "drag", ""), E("ใช้งาน", "groom_station.status", "toggle", "")])],
    [("บันทึก", "stations.upsert", "", "")])
scr("C-44", "console", "/console/settings/import", "นำเข้าข้อมูล CSV", "O", "US-02-08", "ย้ายข้อมูลลูกค้า/น้อง/บริการจากระบบเดิม", ["imports.get"],
    [("ขั้นที่ 1", [W("ชนิดข้อมูล", "import_job.kind", "radio ลูกค้า-น้อง / บริการ", ""), R("ไฟล์ตัวอย่าง", "calc: template CSV", "ปุ่มดาวน์โหลด"),
                    W("ไฟล์", "import_job.file_id", "upload .csv", "R-25")]),
     ("ขั้นที่ 2 ผลตรวจ", [R("ทั้งหมด/ถูก/ผิด", "import_job.total_rows", "3 ตัวเลข (valid_rows, error_rows)"), R("รายการผิด", "import_job.errors", "ตาราง แถว, คอลัมน์, ข้อความ")])],
    [("ตรวจไฟล์", "imports.create", "", ""), ("นำเข้า", "imports.commit", "error_rows = 0", "toast จำนวนที่นำเข้า")])
scr("C-45", "console", "/console/account", "บัญชีของฉัน", "OFS", "US-01-05, US-13-05, US-01-03", "อุปกรณ์ที่ล็อกอิน แจ้งเตือน และ LINE", ["auth.me", "staffMe.sessions"],
    [("โปรไฟล์", [R("ชื่อ", "staff_user.display_name"), R("อีเมล", "staff_user.email"), R("บทบาท", "staff_user.role", "enum")]),
     ("อุปกรณ์", [R("รายการ", "session.user_agent", "ชื่ออุปกรณ์ + last_seen_at + 'เครื่องนี้'")]),
     ("แจ้งเตือน", [W("เปิดแจ้งเตือนบนเครื่องนี้", "web_push_subscription.endpoint", "ปุ่ม (ขอ permission → subscribe)", "iOS ต้อง Add to Home Screen ก่อน (คู่มือ SP-04)")])],
    [("ออกจากระบบเครื่องอื่น", "staffMe.revokeSession", "", ""), ("เปิดแจ้งเตือน", "staffMe.pushSubscribe", "", ""),
     ("ปิดแจ้งเตือนเครื่องนี้", "staffMe.pushUnsubscribe", "มี subscription ของเครื่องนี้", ""), ("ผูก LINE", "staffMe.linkLine", "", "")])
scr("C-46", "console", "(ปุ่มลอยทุกหน้า)", "แจ้งปัญหา / ขอ feature", "OFS", "US-13-13", "ส่ง feedback พร้อมภาพหน้าจอ", [],
    [("ฟอร์ม", [W("เล่าปัญหา/สิ่งที่อยากได้", "feedback_report.message", "textarea", "5–2000"), W("ภาพหน้าจอ", "feedback_report.screenshot_file_id", "แนบ (ไม่บังคับ)", ""),
                R("หน้าปัจจุบัน", "feedback_report.page_url", "auto"), R("เวอร์ชัน", "feedback_report.app_version", "auto")])],
    [("ส่ง", "feedback.create", "", "toast ขอบคุณ")])

# ====================================================================== STAFF APP (PWA, มือถือ)
scr("S-01", "staff", "/staff", "คิวของฉันวันนี้", "OFS", "US-09-03", "ช่างเห็นงานของตัวเองเรียงตามเวลา", ["groom.myQueue"],
    [("การ์ดคิว", [R("เวลา", "groom_appointment.starts_at", "time ตัวใหญ่"), R("น้อง", "pet.name", "รูป + ชื่อ + พันธุ์"), R("ป้ายนิสัย", "pet_temperament_flag.flag", "ไอคอนแดงเด่น"),
                   R("บริการ", "groom_appointment_item.name_snapshot", "list"), R("สถานะ", "groom_appointment.status", "สีการ์ด")])],
    [("แตะการ์ด", "—", "", "→ S-02")], ["ดึงลงเพื่อรีเฟรช; ทำงาน offline อ่านอย่างเดียว (cache ล่าสุด)"])
scr("S-02", "staff", "/staff/appointments/[appointmentId]", "Job card", "OFS", "US-05-07, US-09-03, US-13-04", "ข้อมูลที่ช่างต้องรู้ + ถ่ายรูปก่อน/หลัง + เริ่ม/เสร็จ", ["groom.jobCard"],
    [("สำคัญ (บนสุด)", [R("ป้ายนิสัย", "pet_temperament_flag.flag", "แถบแดง + note"), R("แพ้", "pet_shop_profile.allergies", "แดง"),
                         R("ห้ามใช้แชมพู", "pet_shop_profile.shampoo_avoid", "แดง"), R("โรคประจำตัว", "pet_shop_profile.conditions", "ส้ม")]),
     ("งาน", [R("บริการ + add-on", "groom_appointment_item.name_snapshot", "checklist"), R("ทรงที่ชอบ", "pet_shop_profile.preferred_style", ""),
              R("เบอร์ใบมีด", "pet_shop_profile.blade_no", ""), R("แชมพูที่ใช้ได้", "pet_shop_profile.shampoo_ok", ""),
              R("รูปทรงโปรด", "pet_shop_profile.favorite_style_photo_id", "รูปใหญ่"), R("โน้ตร้าน", "pet_shop_profile.internal_note", ""),
              R("โน้ตลูกค้า", "booking.customer_note", ""), R("สภาพตอนรับ", "groom_appointment.condition_flags", "ป้าย + condition_note"),
              R("น้ำหนักวันนี้", "groom_appointment.weight_grams_checkin", "weight"), R("ครั้งก่อน", "calc: JobCard.lastVisit", "รูป after ครั้งก่อน + โน้ตช่าง")]),
     ("รูป", [W("รูปก่อนทำ", "pet_photo.file_id", "กล้อง (ย่อรูป R-25) kind before", "แนะนำ ≥ 1"), W("รูปหลังทำ", "pet_photo.file_id", "กล้อง kind after", "≥ 1 ก่อนกดเสร็จ ถ้า photo_consent ≠ denied")]),
     ("ปิดงาน", [W("โน้ตถึงร้าน", "groom_appointment.staff_note", "textarea", "≤ 1000")])],
    [("เริ่มงาน", "groom.start", "checked_in", ""), ("ถ่ายรูป", "staff.uploadUrl → photos.add", "", "ย่อรูปฝั่ง client ก่อนอัปโหลด (R-25)"), ("เสร็จงาน", "groom.finish", "in_progress", "→ S-03 Report card"),
     ("แจ้งลูกค้ามารับ", "groom.notifyPickup", "role owner/front_desk, status done", "ซ่อนปุ่มสำหรับ role staff")])
scr("S-03", "staff", "/staff/report-cards/[reportCardId]", "Report card", "OFS", "US-10-01, US-10-02", "ช่างกรอกผลตรวจสั้น ๆ ภายใน 1 นาที", ["reportCards.get"],
    [("ผลตรวจ (ปุ่มใหญ่แตะเลือก)", [E("ผิวหนัง", "report_card.skin", "segmented ปกติ/แห้ง/แดง/มีแผล", "grooming บังคับ"), E("หู", "report_card.ears", "segmented", ""),
        E("เล็บ", "report_card.nails", "segmented", ""), E("ฟัน", "report_card.teeth", "segmented", ""), E("เห็บหมัด", "report_card.parasites", "segmented", ""),
        E("ความร่วมมือ", "report_card.cooperation", "ดาว 1–5", "")]),
     ("ข้อความ", [E("ถึงเจ้าของ", "report_card.staff_note", "textarea + คำแนะนำสำเร็จรูป (chips)", "≤ 500"), E("คำแนะนำ", "report_card.recommendation", "textarea", "≤ 300")]),
     ("พรีวิว", [R("รูปก่อน/หลัง", "pet_photo.file_id", "2 รูป side-by-side"), R("รอบถัดไป", "calc: R-17", "date")])],
    [("บันทึก", "reportCards.update", "", ""), ("ส่ง", "reportCards.submit", "draft", "→ S-01 + toast 'ส่งแล้ว' หรือ 'รอหน้าร้านตรวจ'")])
scr("S-04", "staff", "/staff/care", "งานดูแลวันนี้", "OFS", "US-06-09", "checklist งานโรงแรมตามเวลา", ["careTasks.list"],
    [("ตามเวลา", [R("เวลา", "care_task.due_at", "time; แดงถ้าเลย 30 นาที"), R("งาน", "care_task.title", "ไอคอน + ชื่อยา/ขนาด (medication)"),
                  R("น้อง/ห้อง", "pet.name", "+ room_unit.code"), W("โน้ต", "care_task.note", "chips ด่วน 'กินหมด/เหลือครึ่ง/ไม่กิน' + text", ""),
                  W("รูป", "care_task.photo_file_id", "กล้อง (ไม่บังคับ)", "")])],
    [("ทำแล้ว", "careTasks.done", "pending", ""), ("ข้าม", "careTasks.skip", "pending", "เหตุผล")])
scr("S-05", "staff", "/staff/stays/[stayId]/update", "ส่งอัปเดตน้อง", "OFS", "US-06-10", "ถ่ายรูป/วิดีโอส่งเจ้าของ", ["stays.get"],
    [("อัปเดต", [R("น้อง/ห้อง", "pet.name", "+ room_unit.code"), W("รูป/วิดีโอ", "pet_photo.file_id", "กล้อง 1–6 ไฟล์ (วิดีโอ ≤ 30 วิ)", "R-25"),
                 W("ข้อความ", "pet_photo.caption", "text + chips สำเร็จรูป", "≤ 200"), R("ส่งวันนี้แล้ว", "calc: มี notification stay_update วันนี้", "แจ้ง 'ลูกค้าจะเห็นในหน้าเดิม ไม่ส่งข้อความซ้ำ'")])],
    [("ส่ง", "stays.postUpdate", "checked_in", "")])
scr("S-06", "staff", "/staff/me/commissions", "ค่ามือของฉัน", "OFS", "US-09-05", "ดูค่ามือสะสม", ["staffMe.commissions"],
    [("สรุป", [Q("ช่วง", "calc: from/to", "segmented วันนี้/สัปดาห์/เดือนนี้", ""), R("รวม", "commission_entry.amount_satang", "money ตัวใหญ่"),
               R("รายการ", "commission_entry.base_satang", "วันที่, น้อง, บริการ, money")])])
scr("S-07", "staff", "/staff/me", "ฉัน", "OFS", "US-09-04, US-01-03", "ตั้งค่าแจ้งเตือนและ LINE บนมือถือ", ["auth.me"],
    [("ตั้งค่า", [W("แจ้งเตือน", "web_push_subscription.endpoint", "ปุ่มเปิด + สถานะ", ""), R("LINE", "calc: lineLinked", "ผูกแล้ว/ปุ่มผูก")])],
    [("เปิดแจ้งเตือน", "staffMe.pushSubscribe", "", ""), ("ปิดแจ้งเตือน", "staffMe.pushUnsubscribe", "", ""),
     ("ผูก LINE", "staffMe.linkLine", "", ""), ("ออกจากระบบ", "auth.staffLogout", "", "")])

# ====================================================================== LIFF (ลูกค้า ใน LINE)
scr("L-01", "liff", "/liff/[branchSlug]/register", "ลงทะเบียน", "customer", "US-01-01, US-11-01, US-13-08, US-03-12", "ครั้งแรกที่เปิด LINE ของร้าน", ["liff.session", "liff.shop"],
    [("ต้อนรับ", [R("โลโก้/ชื่อร้าน", "branch.name", "header"), R("รูป/ชื่อ LINE", "line_identity.display_name", "avatar")]),
     ("ข้อมูล", [W("ชื่อ", "owner_profile.first_name", "text (prefill จากชื่อ LINE)", "บังคับ"), W("นามสกุล", "owner_profile.last_name", "text", ""),
                 W("ชื่อเล่น", "owner_profile.nickname", "text", ""), W("เบอร์โทร", "owner_profile.phone_e164", "tel inputmode=numeric", "บังคับ R-22")]),
     ("ความยินยอม", [W("ยอมรับนโยบายความเป็นส่วนตัว", "consent_record.accepted", "checkbox + ลิงก์อ่านฉบับเต็ม (privacy_notice)", "บังคับ"),
                     W("ยอมรับเงื่อนไขการใช้บริการ", "consent_record.accepted", "checkbox (terms_of_service)", "บังคับ"),
                     W("ยินยอมให้ร้านใช้รูปน้อง", "customer.photo_consent", "toggle (ไม่บังคับ)", "")])],
    [("เริ่มใช้งาน", "liff.register", "", "→ L-02; มีคำขอจับคู่ → ข้อความ 'ร้านกำลังตรวจสอบประวัติเดิมของคุณ'")])
scr("L-02", "liff", "/liff/[branchSlug]", "หน้าแรก", "customer", "US-11-03, US-11-08", "เมนูหลักใน LINE", ["liff.shop", "liff.bookings"],
    [("ร้าน", [R("ชื่อร้าน", "branch.name", "header"), R("เวลาเปิดวันนี้", "branch_hours.opens_at", "'เปิด 09:00–18:00'")]),
     ("นัดถัดไป", [R("การ์ด", "booking.first_service_at", "date time + น้อง + สถานะ + ปุ่ม 'จ่ายมัดจำ' ถ้าค้าง")]),
     ("เมนู", [R("จองกรูม", "branch.module_grooming", "ปุ่ม (แสดงเมื่อเปิดโมดูล)"), R("จองโรงแรม", "branch.module_hotel", "ปุ่ม"), R("จอง Daycare", "branch.module_daycare", "ปุ่ม"),
               R("นัดของฉัน / น้องของฉัน / แพ็กเกจ / โปรไฟล์", "calc: links", "ไอคอน")])])
scr("L-03", "liff", "/liff/[branchSlug]/pets | /liff/[branchSlug]/pets/new | /liff/[branchSlug]/pets/[petId]", "น้องของฉัน", "customer", "US-11-02, US-06-05", "ดู/เพิ่ม/แก้ข้อมูลน้อง + ส่งวัคซีน", ["liff.pets"],
    [("รายการ", [R("การ์ดน้อง", "pet.name", "รูป + ชื่อ + พันธุ์ + อายุ + วัคซีนใกล้หมด (แดง)")]),
     ("ฟอร์มน้อง", [E("รูป", "pet.profile_file_id", "upload", ""), E("ชื่อ", "pet.name", "text", "บังคับ"), E("ชนิด", "pet.species", "การ์ดเลือก หมา/แมว/อื่นๆ", "บังคับ"),
        E("พันธุ์", "pet.breed", "combobox ค้นหา", ""), E("เพศ", "pet.sex", "segmented", "บังคับ"), E("วันเกิด", "pet.birth_date", "date (หรือ 'ไม่ทราบ' → อายุโดยประมาณ)", ""),
        E("อายุโดยประมาณ", "pet.age_estimate_months", "ปี + เดือน", ""), E("ทำหมัน", "pet.neutered", "ใช่/ไม่/ไม่ทราบ", ""),
        E("ประเภทขน", "pet.coat_type", "การ์ดพร้อมรูปตัวอย่าง", "บังคับ"), W("น้ำหนักล่าสุด (กก.)", "pet_weight.weight_grams", "number", "ไม่บังคับ")]),
     ("โน้ตจากร้าน", [R("โน้ต", "pet_shop_profile.shared_note", "กล่องฟ้า (เฉพาะ shared_note)")]),
     ("วัคซีน", [R("รายการ", "pet_vaccination.vaccine_code", "ชื่อ + หมดอายุ + สถานะ (รอร้านตรวจ/ยืนยันแล้ว/ไม่ผ่าน+เหตุผล)"),
                 W("เพิ่ม: วัคซีน", "pet_vaccination.vaccine_code", "select", ""), W("หมดอายุ", "pet_vaccination.expires_on", "date", "บังคับ"),
                 W("รูปสมุดวัคซีน", "pet_vaccination.proof_file_id", "กล้อง/อัลบั้ม", "บังคับ")]),
     ("รูป", [R("รูปก่อน-หลังจากร้าน", "pet_photo.file_id", "grid (เฉพาะ kind before/after/stay)")])],
    [("บันทึก", "liff.createPet / liff.updatePet", "", ""), ("ส่งวัคซีน", "customer.uploadUrl → liff.addVaccination", "", "อัปโหลดรูปสมุดวัคซีนก่อน (R-25) แล้วส่ง; toast 'ร้านจะตรวจสอบ'")])
scr("L-04", "liff", "/liff/[branchSlug]/book/grooming", "จองกรูม", "customer", "US-11-03", "4 ขั้น: น้อง → บริการ → วันเวลา → ยืนยัน", ["liff.shop", "liff.pets", "liff.groomSlots", "liff.quote"],
    [("1. น้อง", [W("เลือกน้อง", "groom_appointment.pet_id", "การ์ดน้อง (หลายตัวได้)", "pet active"), W("ขนาด (ถ้าไม่รู้น้ำหนัก)", "groom_appointment.size_tier_id", "การ์ดขนาด + ช่วง กก.", "แสดงเมื่อ no_weight")]),
     ("2. บริการ", [W("บริการหลัก", "groom_appointment_item.service_id", "การ์ด + รูป + ราคาของน้องตัวนี้ (R-02) + เวลา", "≥ 1; online_bookable"),
                    W("Add-on", "groom_appointment_item.service_id", "checkbox + ราคา", "")]),
     ("3. วันเวลา", [W("วันที่", "calc: date", "แถบวัน 14 วัน (ปิดวันที่ร้านปิด)", "R-04 horizon"), W("ช่าง", "groom_appointment.groomer_id", "avatar ช่าง + 'ใครก็ได้'", ""),
                     W("เวลา", "groom_appointment.starts_at", "grid ปุ่มเวลา (R-04)", "ว่าง → 'วันนี้เต็ม ลองวันอื่น'")]),
     ("4. ยืนยัน", [R("สรุป", "calc: Quote", "น้อง, บริการ, วันเวลา, ช่าง, ราคาประเมิน (money)"), R("มัดจำ", "calc: R-06", "money + 'ต้องโอนภายใน 15 นาที'"),
                    R("นโยบายยกเลิก", "branch_policy.policy_text", "กล่องข้อความ"), W("โน้ตถึงร้าน", "booking.customer_note", "textarea", "≤ 300"),
                    W("ยอมรับนโยบาย", "calc: acceptedPolicy", "checkbox", "บังคับ")])],
    [("ยืนยันการจอง", "liff.createBooking", "", "มัดจำ → L-07; ไม่มี → หน้า 'จองสำเร็จ' / 'รอร้านยืนยัน'; SLOT_TAKEN → กลับขั้น 3 + toast")],
    ["ราคาในขั้น 2 เป็น 'ราคาประเมิน' — อาจเปลี่ยนตามน้ำหนักจริงตอนเช็คอิน (แสดงหมายเหตุ)"])
scr("L-05", "liff", "/liff/[branchSlug]/book/hotel", "จองโรงแรม", "customer", "US-11-04, US-11-06", "น้อง → วันที่ → ประเภทห้อง → add-on → ยืนยัน",
    ["liff.pets", "liff.hotelAvailability", "liff.quote"],
    [("1. น้องและวันที่", [W("น้อง", "stay.pet_id", "การ์ด (หลายตัว = หลายการพัก)", ""), W("วันเข้า–ออก", "stay.check_in_date", "range calendar (check_out_date)", "≥ 1 คืน ≤ 30"),
                           W("เวลามาส่ง/รับ", "stay.expected_check_in_time", "select ตามเวลาเปิด (expected_check_out_time)", ""), W("น้องติดสัด", "stay.in_heat", "toggle (เพศเมีย)", "")]),
     ("2. ห้อง", [R("ประเภทห้อง", "room_type.name_th", "การ์ด + รูป + สิ่งอำนวยความสะดวก + ราคา/คืน (money) + 'เหลือ x ห้อง'"),
                  R("ไม่รับน้องตัวนี้", "calc: R-12 reasons", "การ์ดเทา + เหตุผลภาษาไทย"), W("เลือก", "stay.room_type_id", "radio", "")]),
     ("3. เพิ่มเติม", [W("Add-on", "stay_addon.service_id", "checkbox + ราคา (ต่อวัน)", ""),
                       W("อาบน้ำก่อนกลับบ้าน", "stay.bundle_appointment_id", "toggle → เลือกบริการ + เวลาในวันเช็คเอาท์ (R-04)", "US-11-06")]),
     ("4. วัคซีน", [R("ผลตรวจ", "calc: R-11", "✓ ครบ / รายการที่ขาด + ปุ่มอัปโหลด (→ ใบจองรออนุมัติ)")]),
     ("5. ยืนยัน", [R("สรุป", "calc: Quote", "คืน × ราคา + add-on + อาบน้ำ = รวม"), R("มัดจำ", "calc: R-06", "money"), R("นโยบาย", "branch_policy.policy_text", ""),
                    W("ยอมรับนโยบาย", "calc: acceptedPolicy", "checkbox", "บังคับ")])],
    [("ยืนยัน", "liff.createBooking", "", "→ L-07 หรือหน้าสำเร็จ")])
scr("L-06", "liff", "/liff/[branchSlug]/book/daycare", "จอง Daycare", "customer", "US-11-05", "น้อง → วัน+รอบ → ยืนยัน", ["liff.pets", "liff.daycareAvailability", "liff.quote"],
    [("เลือก", [W("น้อง", "daycare_visit.pet_id", "การ์ด", ""), W("วันที่", "daycare_visit.visit_date", "แถบวัน (หลายวันได้)", ""),
                W("รอบ", "daycare_visit.session_type_id", "การ์ด เต็มวัน/เช้า/บ่าย + ที่ว่าง (R-29) + ราคา", "เต็ม = กดไม่ได้"), R("วัคซีน", "calc: R-11", "")]),
     ("ยืนยัน", [R("สรุป", "calc: Quote", "money"), W("ยอมรับนโยบาย", "calc: acceptedPolicy", "checkbox", "บังคับ")])],
    [("ยืนยัน", "liff.createBooking", "", "")])
scr("L-07", "liff", "/liff/[branchSlug]/bookings/[bookingId]/pay", "จ่ายมัดจำ", "customer", "US-11-07, US-07-01, US-05-02", "QR PromptPay + อัปโหลดสลิป ภายในเวลาที่กันคิว", ["liff.booking"],
    [("QR", [R("ยอดที่ต้องโอน", "booking.deposit_required_satang", "money ตัวใหญ่ (− deposit_verified)"), R("QR PromptPay", "calc: R-30", "QR 240px + ปุ่มบันทึกรูป QR"),
             R("ชื่อบัญชี", "branch.promptpay_account_name", "'ตรวจชื่อก่อนโอน'"), R("เหลือเวลา", "booking.hold_expires_at", "นับถอยหลัง mm:ss; หมด → หน้าแจ้งหมดเวลา")]),
     ("ส่งสลิป", [W("รูปสลิป", "payment_slip.file_id", "เลือกจากอัลบั้ม/กล้อง", "R-25"), W("QR บนสลิป", "payment_slip.qr_payload", "อ่านอัตโนมัติจากรูป (jsQR) ไม่แสดงผู้ใช้", "")])],
    [("ส่งสลิป", "customer.uploadUrl → liff.uploadSlip", "awaiting_deposit และ now < hold_expires_at", "→ L-09 สถานะ 'รอร้านตรวจสลิป'; HOLD_EXPIRED → หน้าแจ้งหมดเวลา + ปุ่มจองใหม่")])
scr("L-08", "liff", "/liff/[branchSlug]/bookings", "นัดของฉัน", "customer", "US-11-08", "นัดที่จะมาและที่ผ่านมา", ["liff.bookings"],
    [("แท็บ", [Q("กำลังจะมา/ที่ผ่านมา", "calc: scope", "tabs", "")]),
     ("การ์ด", [R("วันเวลา", "booking.first_service_at", "date (weekday) + time"), R("น้อง", "pet.name", "chips"), R("บริการ", "calc: summary", ""),
                R("สถานะ", "booking.status", "ป้ายภาษาไทย"), R("มัดจำ", "booking.deposit_status", "ป้าย + ปุ่มจ่ายถ้าค้าง"), R("เลขใบจอง", "booking.booking_no", "เล็ก")])])
scr("L-09", "liff", "/liff/[branchSlug]/bookings/[bookingId]", "รายละเอียดนัด", "customer", "US-11-08, US-11-10", "ดู/เลื่อน/ยกเลิก/เพิ่มลงปฏิทิน/นำทาง", ["liff.booking"],
    [("รายละเอียด", [R("สถานะ", "booking.status", "ป้ายใหญ่"), R("เลขใบจอง", "booking.booking_no", ""), R("กรูม", "groom_appointment.starts_at", "date time + น้อง + ช่าง + บริการ"),
                     R("โรงแรม", "stay.check_in_date", "เข้า–ออก + ประเภทห้อง"), R("Daycare", "daycare_visit.visit_date", "วัน + รอบ"),
                     R("ยอดประเมิน", "booking.estimated_total_satang", "money"), R("มัดจำ", "booking.deposit_verified_satang", "money + สถานะ")]),
     ("ยกเลิก", [R("ผลถ้ายกเลิกตอนนี้", "calc: R-07 cancelPreview", "'คืนเครดิต ฿300' / 'ไม่คืนมัดจำ' (แดง)"),
                 W("รับเงินคืนเป็น", "calc: customerChoice", "radio (เฉพาะ customer_choice)", "")])],
    [("เพิ่มลงปฏิทิน", "liff.ics", "", "ดาวน์โหลด .ics"), ("นำทาง", "—", "", "เปิด Google Maps (branch.latitude/longitude)"),
     ("เลื่อนนัด", "liff.groomSlots → liff.reschedule", "R-21 canReschedule", "เลือกเวลาใหม่"), ("ยกเลิก", "liff.cancel", "R-21 canCancel", "dialog ยืนยัน + ผลเงิน"),
     ("จ่ายมัดจำ", "—", "awaiting_deposit", "→ L-07"), ("โทรหาร้าน", "—", "", "tel: branch.phone")],
    ["เหตุผลที่เลื่อนไม่ได้แสดงเป็นข้อความ (TOO_LATE_TO_RESCHEDULE / RESCHEDULE_LIMIT)"])
scr("L-10", "liff", "/liff/[branchSlug]/stays/[stayId]", "อัปเดตน้องระหว่างพัก", "customer", "US-06-10", "ดูรูป/วิดีโอและงานดูแลที่ทำแล้ว", ["liff.stayUpdates"],
    [("หัว", [R("น้อง", "pet.name", "รูป + ชื่อ"), R("ช่วงพัก", "stay.check_in_date", "date – date (check_out_date)")]),
     ("ฟีด", [R("รูป/วิดีโอ", "pet_photo.file_id", "การ์ดใหม่→เก่า + caption + เวลา (taken_at)"),
              R("งานที่ทำแล้ววันนี้", "care_task.title", "'🍽 ให้อาหาร 08:05 – กินหมด' (done_at, note)")])])
scr("L-11", "liff", "/liff/[branchSlug]/report-cards/[reportCardId]", "Report card", "customer", "US-10-01, US-10-02, US-10-03", "ผลหลังบริการ + ให้ดาว + ลิงก์รีวิว", ["liff.reportCard"],
    [("ผล", [R("รูปก่อน/หลัง", "pet_photo.file_id", "slider before/after"), R("บริการที่ทำ", "groom_appointment_item.name_snapshot", "list"),
             R("ผลตรวจ", "report_card.skin", "ไอคอน + ข้อความไทย ผิว/หู/เล็บ/ฟัน/เห็บหมัด"), R("ความร่วมมือ", "report_card.cooperation", "ดาว"),
             R("ข้อความจากช่าง", "report_card.staff_note", "ชื่อช่าง + ข้อความ"), R("คำแนะนำ", "report_card.recommendation", ""),
             R("รอบถัดไป", "calc: R-17", "date + ปุ่มจองเลย")]),
     ("ให้คะแนน", [E("ความพอใจ", "report_card.customer_rating", "ดาว 1–5", ""), E("ข้อความถึงร้าน", "report_card.customer_feedback", "textarea (ร้านเห็นเท่านั้น)", "≤ 1000")]),
     ("รีวิว", [R("รีวิวบน Google", "branch_policy.google_review_url", "ปุ่มแสดงกับทุกคน ไม่ขึ้นกับดาว")])],
    [("ส่งคะแนน", "liff.rate", "", "ขอบคุณ"), ("รีวิวบน Google", "liff.reviewClick", "มี google_review_url", "เปิดลิงก์ภายนอก"), ("จองรอบถัดไป", "—", "", "→ L-04")])
scr("L-12", "liff", "/liff/[branchSlug]/packages", "แพ็กเกจของฉัน", "customer", "US-10-06", "สิทธิ์คงเหลือ", ["liff.packages"],
    [("การ์ด", [R("แพ็กเกจ", "package_template.name_th", ""), R("น้อง", "pet.name", "หรือ 'ทุกตัวในบ้าน'"), R("คงเหลือ", "calc: sessions_total − sessions_used", "'เหลือ 3/5 ครั้ง' + progress"),
                R("หมดอายุ", "customer_package.expires_at", "date; ส้มถ้า < 30 วัน"), R("สถานะ", "customer_package.status", "ป้าย")])])
scr("L-13", "liff", "/liff/[branchSlug]/receipts/[billId]", "ใบเสร็จ", "customer", "US-08-05", "ใบเสร็จอิเล็กทรอนิกส์", ["liff.receipt"],
    [("ใบเสร็จ", [R("ร้าน", "branch.name", "หัว"), R("เลขที่/วันที่", "bill.receipt_no", "+ closed_at"), R("รายการ", "bill_line.description", "qty × ราคา = รวม"),
                  R("ส่วนลด", "bill.bill_discount_satang", "money"), R("ยอดสุทธิ", "bill.total_satang", "money always"), R("ชำระโดย", "payment.method", ""),
                  R("แพ็กเกจคงเหลือ", "customer_package.sessions_used", "")])],
    [("บันทึกรูป", "—", "", "html → PNG (client) เพื่อแชร์")])
scr("L-14", "liff", "/liff/[branchSlug]/pay/[billId]", "จ่ายยอดคงเหลือ", "customer", "US-07-08", "QR ยอดค้างของบิล + ส่งสลิป", ["liff.payPage"],
    [("QR", [R("ยอดค้าง", "calc: bill.total_satang − bill.paid_satang", "money ตัวใหญ่"), R("QR", "calc: R-30", "QR"), R("ชื่อบัญชี", "branch.promptpay_account_name", "")]),
     ("สลิป", [W("รูปสลิป", "payment_slip.file_id", "upload", ""), W("QR บนสลิป", "payment_slip.qr_payload", "อ่านอัตโนมัติ", "")])],
    [("ส่งสลิป", "liff.payUploadSlip", "bill open และค้าง > 0", "ข้อความรอร้านตรวจ")])
scr("L-15", "liff", "/liff/[branchSlug]/me", "โปรไฟล์ของฉัน", "customer", "US-11-01, US-03-12, US-13-08", "แก้ข้อมูลติดต่อ ความยินยอม และสิทธิ์ PDPA", ["liff.me"],
    [("ข้อมูล", [E("ชื่อ", "owner_profile.first_name", "text", "บังคับ"), E("นามสกุล", "owner_profile.last_name", "text", ""), E("ชื่อเล่น", "owner_profile.nickname", "text", ""),
                 E("เบอร์โทร", "owner_profile.phone_e164", "tel", "R-22"), E("อีเมล", "owner_profile.email", "email", "")]),
     ("เครดิต", [R("เครดิตคงเหลือ", "customer.credit_balance_satang", "money")]),
     ("ความยินยอม", [E("ให้ร้านใช้รูปน้อง", "customer.photo_consent", "toggle", "บันทึก consent_record ใหม่")]),
     ("สิทธิ์ของฉัน (PDPA)", [W("ขอสำเนาข้อมูล / ขอลบข้อมูล", "data_request.type", "2 ปุ่ม + dialog อธิบายผล", "")])],
    [("บันทึก", "liff.updateMe", "", ""), ("ส่งคำขอ", "liff.dataRequest", "", "toast 'ทีมงานจะติดต่อภายใน 30 วัน'")])

# ====================================================================== ADMIN
scr("AD-01", "admin", "/admin/login", "Admin login", "admin", "US-13-10", "ทีมแพลตฟอร์มเข้าระบบ", [],
    [("ฟอร์ม", [W("อีเมล", "platform_admin.email", "email", ""), W("รหัสผ่าน", "platform_admin.password_hash", "password", "")])], [("เข้าสู่ระบบ", "admin.login", "", "→ AD-02")])
scr("AD-02", "admin", "/admin/organizations", "ร้านทั้งหมด", "admin", "US-13-10, US-13-14", "ดูและสร้างร้านนำร่อง", ["admin.orgs"],
    [("ตาราง", [R("ร้าน", "organization.name"), R("slug", "organization.slug", "mono"), R("สถานะ", "organization.status", "enum"), R("เจ้าของ", "staff_user.email"),
                R("LINE", "line_channel.status", "enum"), R("ใช้งานล่าสุด", "calc: lastActivityAt", "time ago")]),
     ("สร้างร้าน", [W("ชื่อธุรกิจ", "organization.name", "text", ""), W("slug", "organization.slug", "text", "a-z0-9-"), W("ชื่อสาขา", "branch.name", "text", ""),
                    W("ลิงก์จอง", "branch.booking_slug", "text", "a-z0-9-"), W("อีเมลเจ้าของ", "staff_user.email", "email", ""), W("ชื่อเจ้าของ", "staff_user.display_name", "text", ""),
                    W("โมดูล", "branch.module_grooming", "3 checkbox (module_hotel, module_daycare)", "")])],
    [("สร้าง", "admin.createOrg", "", "แสดงลิงก์เชิญเจ้าของ")])
scr("AD-03", "admin", "/admin/organizations/[orgId]", "ร้าน (admin)", "admin", "US-02-06, US-13-10, US-13-11", "ตั้งค่า LINE ของร้าน สถานะ และเข้าโหมดช่วยเหลือ", ["admin.orgs"],
    [("สถานะ", [E("สถานะร้าน", "organization.status", "select", "")]),
     ("LINE OA (ตาม ADR-001)", [E("Provider ID", "line_channel.provider_id", "text", ""), E("Messaging channel ID", "line_channel.messaging_channel_id", "text", ""),
        W("Channel secret", "line_channel.channel_secret_enc", "password (ไม่แสดงค่าเดิม)", ""), W("Channel access token", "line_channel.channel_access_token_enc", "password", ""),
        E("LINE Login channel ID", "line_channel.login_channel_id", "text", ""), E("LIFF ID", "line_channel.liff_id", "text", ""), E("Basic ID", "line_channel.bot_basic_id", "text @xxx", ""),
        E("โควตา push/เดือน", "line_channel.monthly_push_quota", "number", ""), R("Webhook URL", "calc: /api/webhooks/line/{messagingChannelId}", "copy"),
        R("ตรวจล่าสุด", "line_channel.webhook_verified_at", "date time"), R("สถานะการเชื่อม", "line_channel.status", "enum badge")]),
     ("โหมดช่วยเหลือ", [W("เหตุผล", "support_access_log.reason", "textarea", "≥ 10"), W("อ้างอิง", "support_access_log.ticket_ref", "text", "")])],
    [("บันทึกสถานะ", "admin.updateOrg", "", ""), ("บันทึก LINE", "admin.setLineChannel", "", ""), ("ทดสอบ + ตั้ง webhook", "admin.verifyLine", "", ""),
     ("เข้าโหมดช่วยเหลือ", "admin.supportStart", "", "เปิด console ของร้านแบบอ่านอย่างเดียว (แถบแดงด้านบน)"),
     ("จบโหมดช่วยเหลือ", "admin.supportEnd", "มี support session เปิดอยู่", "ปุ่มบนแถบแดงใน console ด้วย — หมดอายุเองใน 60 นาที")])
scr("AD-04", "admin", "/admin/feedback", "Feedback", "admin", "US-13-13", "แจ้งปัญหาจากร้าน", ["admin.feedback"],
    [("ตาราง", [R("ร้าน", "organization.name"), R("ผู้แจ้ง", "staff_user.display_name"), R("ข้อความ", "feedback_report.message"), R("หน้า", "feedback_report.page_url", "link"),
                R("ภาพ", "feedback_report.screenshot_file_id", "thumbnail"), E("สถานะ", "feedback_report.status", "select", "")])],
    [("เปลี่ยนสถานะ", "admin.updateFeedback", "", "")])
scr("AD-05", "admin", "/admin/data-requests", "คำขอ PDPA", "admin", "US-13-08", "จัดการคำขอดู/ลบข้อมูล ภายใน 30 วัน", ["admin.dataRequests"],
    [("ตาราง", [R("ร้าน", "organization.name"), R("ประเภท", "data_request.type", "enum"), R("สถานะ", "data_request.status", "enum"), R("ขอเมื่อ", "data_request.created_at", "date + วันคงเหลือจาก 30"),
                W("บันทึก", "data_request.note", "textarea", "")])],
    [("ดำเนินการ", "admin.resolveDataRequest", "open", "dialog ยืนยัน (ลบ = ย้อนไม่ได้)")])
scr("AD-06", "admin", "/admin/analytics", "Analytics นำร่อง", "admin", "US-13-12", "วัดผลร้านนำร่อง", ["admin.analytics"],
    [("ตาราง", [R("ร้าน", "organization.name"), R("วันที่ใช้งานใน 7 วัน", "calc: activeDays7", "number"), R("จองออนไลน์ %", "calc: onlineShare", "percent"),
                R("No-show %", "calc: noShowRate", "percent"), R("Push ที่ใช้", "calc: pushUsed", "number"), R("บิลที่ปิด", "calc: billsClosed", "number")])])
scr("AD-07", "admin", "/admin/holidays", "วันหยุดราชการ", "admin", "US-13-03", "seed วันหยุดประจำปี", [],
    [("ปี", [E("วันที่", "public_holiday.holiday_date", "date", ""), E("ชื่อวันหยุด", "public_holiday.name_th", "text", "")])], [("บันทึก", "admin.holidays", "", "")])

ENUM_LABELS = {
 "staff_role": {"owner": "เจ้าของร้าน", "front_desk": "หน้าร้าน", "staff": "พนักงาน/ช่าง"},
 "staff_status": {"invited": "รอรับคำเชิญ", "active": "ใช้งาน", "disabled": "ปิดใช้งาน"},
 "species": {"dog": "หมา", "cat": "แมว", "other": "อื่นๆ"},
 "pet_sex": {"male": "ผู้", "female": "เมีย", "unknown": "ไม่ทราบ"},
 "pet_status": {"active": "ปกติ", "deceased": "จากไปแล้ว", "rehomed": "ย้ายบ้าน"},
 "coat_type": {"short": "ขนสั้น", "long": "ขนยาว", "double": "ขนสองชั้น", "curly": "ขนหยิก", "wire": "ขนลวด", "hairless": "ไม่มีขน", "unknown": "ไม่ทราบ"},
 "coat_group": {"short": "ขนสั้น", "long": "ขนยาว", "any": "ทุกแบบ"},
 "temperament_flag": {"bites": "กัด", "needs_muzzle": "ต้องใส่ตะกร้อ", "dryer_fear": "กลัวไดร์", "noise_sensitive": "กลัวเสียง",
                      "same_groomer_only": "ช่างคนเดิมเท่านั้น", "dog_reactive": "ไม่ถูกกับหมา", "cat_reactive": "ไม่ถูกกับแมว", "anxious": "ขี้กังวล", "other": "อื่นๆ"},
 "vaccine_status": {"pending_review": "รอร้านตรวจ", "verified": "ยืนยันแล้ว", "rejected": "ไม่ผ่าน"},
 "photo_consent": {"unknown": "ยังไม่ถาม", "granted": "ยินยอม", "denied": "ไม่ยินยอม"},
 "closure_scope": {"all": "ทั้งร้าน", "grooming": "กรูม", "hotel": "โรงแรม", "daycare": "Daycare"},
 "deposit_type": {"none": "ไม่เก็บ", "fixed": "จำนวนคงที่", "percent": "เปอร์เซ็นต์"},
 "cancel_refund_mode": {"refund": "คืนเงิน", "credit": "คืนเป็นเครดิต", "customer_choice": "ให้ลูกค้าเลือก"},
 "promptpay_type": {"phone": "เบอร์มือถือ", "national_id": "เลขบัตรประชาชน", "tax_id": "เลขผู้เสียภาษี", "ewallet": "e-Wallet"},
 "line_channel_status": {"pending": "รอตั้งค่า", "active": "เชื่อมแล้ว", "error": "มีปัญหา"},
 "service_scope": {"grooming": "กรูม", "hotel": "โรงแรม", "daycare": "Daycare"},
 "service_category": {"bath": "อาบน้ำ", "haircut": "ตัดขน", "spa": "สปา", "nail": "ตัดเล็บ", "ear": "ทำความสะอาดหู", "teeth": "ทำความสะอาดฟัน",
                      "deshed": "ลดขนร่วง", "other": "อื่นๆ", "hotel_addon": "เสริมโรงแรม", "daycare_addon": "เสริม Daycare"},
 "room_unit_status": {"active": "ใช้งาน", "maintenance": "ซ่อม", "archived": "เลิกใช้"},
 "housekeeping_status": {"clean": "สะอาด", "dirty": "ต้องทำความสะอาด"},
 "daycare_session": {"full_day": "เต็มวัน", "morning": "ครึ่งเช้า", "afternoon": "ครึ่งบ่าย"},
 "booking_channel": {"walk_in": "walk-in", "phone": "โทรศัพท์", "chat": "แชท", "line_liff": "LINE", "booking_link": "ลิงก์จอง", "ota": "แพลตฟอร์มจอง", "import": "นำเข้า"},
 "booking_status": {"awaiting_deposit": "รอโอนมัดจำ", "deposit_review": "รอร้านตรวจสลิป", "awaiting_approval": "รอร้านยืนยัน",
                    "confirmed": "ยืนยันแล้ว", "cancelled": "ยกเลิก", "expired": "หมดเวลา", "closed": "เสร็จสิ้น"},
 "deposit_status": {"not_required": "ไม่ต้องมัดจำ", "pending": "ค้างมัดจำ", "submitted": "ส่งสลิปแล้ว", "verified": "รับมัดจำแล้ว", "rejected": "สลิปไม่ผ่าน",
                    "refunded": "คืนเงินแล้ว", "credited": "คืนเป็นเครดิต", "forfeited": "ริบมัดจำ", "applied": "หักในบิลแล้ว"},
 "groom_status": {"scheduled": "นัดไว้", "checked_in": "มาถึงแล้ว", "in_progress": "กำลังทำ", "done": "เสร็จ รอรับ", "picked_up": "รับกลับแล้ว",
                  "no_show": "ไม่มา", "cancelled": "ยกเลิก"},
 "stay_status": {"reserved": "จองแล้ว", "checked_in": "พักอยู่", "checked_out": "กลับบ้านแล้ว", "no_show": "ไม่มา", "cancelled": "ยกเลิก"},
 "daycare_status": {"reserved": "จองแล้ว", "checked_in": "อยู่ในร้าน", "checked_out": "กลับแล้ว", "no_show": "ไม่มา", "cancelled": "ยกเลิก"},
 "care_task_type": {"feed": "ให้อาหาร", "medication": "ให้ยา", "walk": "พาเดิน", "clean": "ทำความสะอาด", "other": "อื่นๆ"},
 "care_task_status": {"pending": "รอทำ", "done": "ทำแล้ว", "skipped": "ข้าม"},
 "slip_status": {"submitted": "รอตรวจ", "verified": "ยืนยันแล้ว", "rejected": "ไม่ผ่าน"},
 "payment_method": {"cash": "เงินสด", "promptpay": "PromptPay", "bank_transfer": "โอนเงิน", "card_edc": "บัตร", "deposit": "มัดจำ", "credit": "เครดิต"},
 "refund_mode": {"bank_transfer": "โอนคืน", "cash": "เงินสด", "credit": "เครดิต"},
 "credit_reason": {"cancellation_credit": "เครดิตจากการยกเลิก", "deposit_credit": "มัดจำส่วนเกิน", "bill_payment": "ใช้ชำระบิล", "void_reversal": "ย้อนรายการ", "adjustment": "ปรับโดยร้าน"},
 "bill_status": {"open": "กำลังคิดเงิน", "paid": "ชำระแล้ว", "void": "ยกเลิก"},
 "bill_line_type": {"groom_service": "บริการกรูม", "groom_addon": "Add-on", "surcharge": "ค่าบริการเพิ่ม", "stay_night": "ค่าห้อง", "stay_addon": "เสริมโรงแรม",
                    "daycare": "Daycare", "quick_item": "สินค้า/บริการ", "package_sale": "ขายแพ็กเกจ", "package_redemption": "ใช้สิทธิ์แพ็กเกจ"},
 "customer_package_status": {"active": "ใช้ได้", "exhausted": "ใช้ครบแล้ว", "expired": "หมดอายุ", "void": "ยกเลิก"},
 "report_card_status": {"draft": "ร่าง", "pending_review": "รอตรวจ", "sent": "ส่งแล้ว"},
 "skin_condition": {"normal": "ปกติ", "dry": "แห้ง", "redness": "แดง/ระคายเคือง", "lesion": "มีแผล/ตุ่ม"},
 "ear_condition": {"clean": "สะอาด", "dirty": "มีขี้หูมาก", "suspected_infection": "สงสัยติดเชื้อ"},
 "nail_condition": {"trimmed": "ตัดแล้ว", "ok": "ปกติ", "overgrown": "ยาวเกิน"},
 "teeth_condition": {"ok": "ปกติ", "tartar": "มีหินปูน", "bad_breath": "มีกลิ่นปาก"},
 "parasite_finding": {"none": "ไม่พบ", "fleas": "พบหมัด", "ticks": "พบเห็บ", "both": "พบทั้งเห็บและหมัด"},
 "notification_skip_reason": {"quota_exhausted": "โควตาข้อความหมด", "economy_mode": "โหมดประหยัด", "pet_inactive": "น้องไม่อยู่แล้ว",
                              "no_recipient": "ลูกค้ายังไม่ได้เพิ่มเพื่อน LINE", "opted_out": "ลูกค้าปิดการแจ้งเตือน", "duplicate": "ส่งซ้ำ"},
 "data_request_type": {"access": "ขอสำเนาข้อมูล", "delete": "ขอลบข้อมูล"},
 "org_status": {"pilot": "นำร่อง", "active": "ใช้งาน", "suspended": "ระงับ"},
 "commission_type": {"percent": "เปอร์เซ็นต์", "fixed": "บาทต่อครั้ง"},
 "package_share_scope": {"single_pet": "น้องตัวเดียว", "household": "ทุกตัวในบ้าน"},
 "groomer_preference": {"any": "ใครก็ได้", "specific": "ระบุช่าง"},
}
