#!/usr/bin/env python3
"""Bundle / unbundle the HAND-WRITTEN kit files (everything not generated by tools/spec-src) into one text file.
Used for checkpoints: `python3 tools/kit_bundle.py pack out.md` · `python3 tools/kit_bundle.py unpack in.md [root]`"""
import os, sys, fnmatch
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
GENERATED = ["docs/spec/0[2-9]-*.md", "docs/spec/10-*.md", "docs/spec/enum-labels.th.json", "docs/spec/vectors/*", "docs/tasks/*",
             "packages/db/src/schema/*", "tools/_custom_constraints.sql", "tools/spec-src/*", "tools/spec-src/selftest/*",
             "*/node_modules/*", "node_modules/*", "*.zip", "*/__pycache__/*", "pnpm-lock.yaml", "packages/db/migrations/*"]
MARK = "===== FILE: "
def files():
    for d, dirs, fs in os.walk(ROOT):
        dirs[:] = [x for x in dirs if x not in ("node_modules", ".git", "__pycache__", ".next")]
        for f in fs:
            rel = os.path.relpath(os.path.join(d, f), ROOT)
            if not any(fnmatch.fnmatch(rel, g) for g in GENERATED): yield rel
if sys.argv[1] == "pack":
    out = []
    for rel in sorted(files()):
        out.append(f"{MARK}{rel} =====\n" + open(os.path.join(ROOT, rel), encoding="utf-8").read())
    open(sys.argv[2], "w", encoding="utf-8").write("\n".join(out)); print(len(out), "files")
else:
    root = sys.argv[3] if len(sys.argv) > 3 else ROOT
    cur, buf, n = None, [], 0
    def flush():
        global n
        if cur:
            p = os.path.join(root, cur); os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
            open(p, "w", encoding="utf-8").write("\n".join(buf)); n += 1
    for line in open(sys.argv[2], encoding="utf-8").read().split("\n"):
        if line.startswith(MARK) and line.endswith(" ====="):
            flush(); cur, buf = line[len(MARK):-6], []
        else: buf.append(line)
    flush(); print(n, "files restored to", root)
